### ISSUE TITLE
Drag & Drop disable

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#10]
How do I disable passive drag and drop?
And how can I select the time interval I want and run a function?

**Comment by emrahnalci** [comment]
And last question.
How can i use ajax load data ?

**Comment by vkurko** [comment]
Hi @emrahnalci 

To disable the drag&drop you need to set both [editable](https://github.com/vkurko/calendar#editable) and [eventStartEditable](https://github.com/vkurko/calendar#eventstarteditable) to `false` (the `editable` is set to `false` by default).

To load the events data from a URL via AJAX you should use [eventSources](https://github.com/vkurko/calendar#eventsources) option. The Event Calendar will send requests to the specified URL whenever it needs new event data. The request will include the `start` and `end` parameters (ISO8601 date strings) which specify the date-range that the calendar needs events for. The expected response format is JSON with the [events data](https://github.com/vkurko/calendar#parsing-event-from-a-plain-object).
