### ISSUE TITLE
Selection is not cleared

### ISSUE THREAD

**Issue by LisPavel** [vkurko/calendar#100]
When I call unselect method from callback select nothing happens.
I'm just trying to add new event after select and clear selection.
```js
function createNewEvent({ start, end }) {
    calendar.addEvent({
        id: crypto.randomUUID(),
        start,
        end,
        title: crypto.randomUUID(),
    });
    calendar.unselect();
}
```

Maybe I'm doing something wrong?

**Comment by vkurko** [comment]
@LisPavel Please try the new version 0.17.1.

**Comment by LisPavel** [comment]
@vkurko It just work! Thanks

**Comment by vkurko** [comment]
Great :smile:
