### ISSUE TITLE
Possibility to use some events as background events?

### ISSUE THREAD

**Issue by mrvnklm** [vkurko/calendar#101]
Is there a possibility to use some events as background events so other events don't move to the side?
My specific example is, that I have an availability which should be a block in the background containing multiple events inside which not overlap and therefor should not move to the right.

Here an example I did by just adjusting css manually:
<img width="271" alt="Screenshot 2023-04-13 at 11 14 09" src="https://user-images.githubusercontent.com/24477241/231715448-1a866934-ff2c-4579-804e-f73415c92d84.png">

EDIT: I made a mistake using `display: "background"`, so now it works but is there a way to show any times or titles in the background event?

**Comment by vkurko** [comment]
Yes, background events are supported and such events must have the `display: "background"` attribute. By default they don't render any content, but you can override this in the [eventContent](https://github.com/vkurko/calendar#eventcontent) callback.

**Comment by mrvnklm** [comment]
Alright, thanks a lot for your fast response!
