### ISSUE TITLE
Can't hide days in specific view

### ISSUE THREAD

**Issue by LisPavel** [vkurko/calendar#107]
I'm trying to hide Sat and Sun in week grid but it doesn't work.
```js
const calendar = new Calendar({
    ...,
    views: {
        timeGridWeek: {
            hiddenDays: [0, 6],
        },
    },
});
```

**Comment by vkurko** [comment]
In this [demo](https://jsbin.com/fenatojusa/edit?js,output) everything seems to work as expected. Please let me know how to reproduce the issue.

**Comment by LisPavel** [comment]
sorry, it's my mistake
