### ISSUE TITLE
Using eventContent creates error on hover

### ISSUE THREAD

**Issue by jnegron357** [vkurko/calendar#109]
I added a function for the eventContent property and started seeing an error when I hover over other dates and times in the week view.
![event-calendar-bug](https://user-images.githubusercontent.com/3504712/234102198-7e15e0cd-a198-4ef3-8aee-a40e37b34f69.png)

**Comment by vkurko** [comment]
Please see my [comment](https://github.com/vkurko/calendar/discussions/108#discussioncomment-5728073) and new [demo](https://jsbin.com/pomijizoyi/edit?js,output).

**Comment by vkurko** [comment]
I hope I can close this issue.
