### ISSUE TITLE
filterResourcesWithEvents about

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#111]
Hi Vladimir Kurko,
I have some questions.

1-) Can we hide resourceTimeGridDay hide columns like timeGridWeek: {hiddenDays: [2,3,4,5]} etc.
2-) About popover again

EventDidMount showing popover no problem but if i want to drag drop event i cant hide popover (Bootstrap 5)

```
<script>
let ec = new EventCalendar(document.getElementById('ec'), {
view: 'resourceTimeGridDay', height: '800px',
eventDidMount: function(info) {
            if (info.event.display === 'auto') {
                const bsPopover = new bootstrap.Popover(info.el, {
                    placement: 'left', trigger: 'hover', html: true,
                    title: function(){ return info.event.title; },
                    content: function(){ return info.event.extendedProps[0].explanation; }
                });
            }
        },
        eventDragStart: function (info) {
            // i cant run popover hide method here
            // const bsPopover = new bootstrap.Popover(info.el);
            // bsPopover.hide()
            // $('.ec-event').bsPopover.hide();
        },

    });</script>
```

3-) when i use refetchEvents() function can i change resources and events data ?

Thank you for you support

**Comment by vkurko** [comment]
Hi @emrahnalci 

1) Can you explain what you mean. Sorry, I don't quite understand the issue.
2) Do you have a codepen link please?
3) You can use a function as the value for [eventSources](https://github.com/vkurko/calendar#eventsources). In this case, inside the function there can be any business logic that can manage both the parameters passed to the server and change the data received from the server before passing them to the calendar.

**Comment by emrahnalci** [comment]
1-) [your example](https://jsbin.com/fenatojusa/edit?js,output) i want to same job but resourceTimeGridDay

2-) [jsfiddle](https://jsfiddle.net/AENMaster/oz6jmrpg/9/)
if i change (right on refresh button) selectbox rooms or personal **code is line 110**
`<script>
$('#resourceView').change(function(){
    if($(this).val() == 1){
      ec.view('resourceTimeGridDay').resources([
        {id: 1, title: 'Personal\n 1'},{id: 2, title: 'Personal\n 2'},
        {id: 3, title: 'Personal\n 3'},{id: 4, title: 'Personal\n 4'}
      ]).events(
        personalEvents()
      );
    }
    else {
      ec.view('resourceTimeGridDay').resources([
        {id: 1, title: 'Room\n 1'},{id: 2, title: 'Room\n 2'},
        {id: 3, title: 'Room\n 3'},{id: 4, title: 'Room\n 4'},
        {id: 5, title: 'Room\n 5'},{id: 6, title: 'Room\n 6'},
        {id: 7, title: 'Room\n 7'},{id: 8, title: 'Room\n 8'},
        {id: 9, title: 'Room\n 9'},{id: 10, title: 'Room\n 10'},
        {id: 11, title: 'Room\n 11'},{id: 12, title: 'Room\n 12'}
      ]).events(
        roomEvents()
      );
    }
  });
</script>`

3-) refresh button code on line 169

**Comment by vkurko** [comment]
1) 'hiddenDays' options works for `resourceTimeGridDay` view too. I do not see the issue. Please, provide a link to a demo showing the problem.
2) I hover over an event and see a popup. I start moving the event and the popup hides. What exactly is the problem?
3) With all due respect to all those who use the Event Calendar in their projects and help me identify bugs in the calendar, fix them and improve the library, I have no way to help you write the code for your business logic. I pointed out the options and features that I think can be used in your case, but I will not write code for your project. Hope for understanding :smile:

**Comment by vkurko** [comment]
1) `hiddenDays` option works for `resourceTimeGridDay` view too. I do not see the issue. Please, provide a link to a demo showing the problem.
2) I hover over an event and see a popup. I start moving the event and the popup hides. What exactly is the problem?
3) With all due respect to all those who use the Event Calendar in their projects and help me identify bugs in the calendar, fix them and improve the library, I have no way to help you write the code for your business logic. I pointed out the options and features that I think can be used in your case, but I will not write code for your project. Hope for understanding :smile:

**Comment by vkurko** [comment]
1. here is a new [demo](https://jsbin.com/witikapuba/edit?js,output)

**Comment by emrahnalci** [comment]
Thank you resourceTimeGridDay hiddenDays 
Now i see my wrong code 
Thank your support 
You can close 😄
