### ISSUE TITLE
Editable ability can not be disabled?

### ISSUE THREAD

**Issue by dimakovalevskyi** [vkurko/calendar#113]
I create simple calendar instance, I want only viewing events, not editing.

`editable: false` option does nothing. My event on calendar still can be dragged between days and resized.

Should this option disable this abilities? Or how can i make read-only mode for calendar. Thanks!

Here is simple example.
https://codepen.io/dimakovalevskyi/pen/ZEqKRjd

**Comment by dimakovalevskyi** [comment]
Really it works! Thank you a lot!

**Comment by 4d4ch4u32** [comment]
Please update this information in the main documentation.

**Comment by vkurko** [comment]
> Please update this information in the main documentation.

Please explain how exactly the documentation can be improved.
