### ISSUE TITLE
Event Text Color

### ISSUE THREAD

**Issue by stackasaur** [vkurko/calendar#116]
So it doesn't seem there is an out-of-the-box option for setting Event text color?

I believe this would be a better use of the `color` attribute currently aliases the background color to more align with CSS property names. But to not cause any breaking changing, I propose `textColor` as an attribute name.

Alternatively, event could take in a list/string of class names or styles to apply.

My thought is that basing the text color entirely on the event class through theming really limits the number of colors you can have for events.

If I'm missing an easier way to do this currently, please let me know, but otherwise, I could work on this change.

**Comment by vkurko** [comment]
@stackasaur Thanks a lot for your contribution. I don't have a chance to review your PR right now, so give me some more time please. I would also prefer separate PRs for each new feature.

**Comment by vkurko** [comment]
Thanks to @stackasaur this was implemented in v1.1.0.

**Comment by darkvovich** [comment]
Hi! className / classNames in event obj not working for me

try to add as string and ass array of classes

How to use it's correctly?

**Comment by vkurko** [comment]
> How to use it's correctly?

[Here](https://jsbin.com/nafibakaxu/edit?html,output) I added the `TEST` class to the event with the text `The calendar can display background and regular events`. So it's just `className: "TEST"`.
