### ISSUE TITLE
feature to add link to event

### ISSUE THREAD

**Issue by victorDigital** [vkurko/calendar#117]
a feature I would like to see is the possibility of adding a link to a calendar event like a 
```
<a href="..."> normal event HTML here </a>
```

ps.
if you try to do this currently by modifying the `event.el.outerHTML` of the event and wrapping it in an `a` tag you no longer are able to switch weeks

A sleek implementation that allows this feature is adding another event object property e.g. `backgroundColor`

thanks from Copenhagen, Denmark 😎✌️

**Comment by vkurko** [comment]
> I would like to see is the possibility of adding a link to a calendar event

Did you check [eventContent](https://github.com/vkurko/calendar#eventcontent) settings? It allows you to display absolutely any content inside the events.

> adding another event object property e.g. `backgroundColor`

`backgroundColor` is supported. Please see [here](https://github.com/vkurko/calendar#parsing-event-from-a-plain-object).

**Comment by vkurko** [comment]
> I would like to see is the possibility of adding a link to a calendar event

Did you check [eventContent](https://github.com/vkurko/calendar#eventcontent) setting? It allows you to display absolutely any content inside the events.

> adding another event object property e.g. `backgroundColor`

`backgroundColor` is supported. Please see [here](https://github.com/vkurko/calendar#parsing-event-from-a-plain-object).
