### ISSUE TITLE
Events with Ajax

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#12]
How can i send date and load with ajax ?

**Comment by vkurko** [comment]
Hi @emrahnalci 

To load the events data from a URL via AJAX you should use [eventSources](https://github.com/vkurko/calendar#eventsources) option. The Event Calendar will send requests to the specified URL whenever it needs new event data. The request will include the `start` and `end` parameters (ISO8601 date strings) which specify the date-range that the calendar needs events for. The expected response format is JSON with the [events data](https://github.com/vkurko/calendar#parsing-event-from-a-plain-object).
