### ISSUE TITLE
Editable Option not Working

### ISSUE THREAD

**Issue by PedroYuriAlves** [vkurko/calendar#127]
editable option is not working, neither in master editable nor for each event.

--------------------------------------------------------------------------------------------
new EventCalendar(document.getElementById('calendar'), {
        view: 'timeGridWeek',
        height: '800px',
        headerToolbar: {
            start: 'prev,next today',
            center: 'title',
            end: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek resourceTimeGridWeek'
        },
        buttonText: function (texts) {
            texts.resourceTimeGridWeek = 'resources';
            return texts;
        },
        resources: [
            { id: 1, title: 'Resource A' },
            { id: 2, title: 'Resource B' }
        ],
        scrollTime: '09:00:00',
        events: createEvents(),
        views: {
            timeGridWeek: { pointer: true },
            resourceTimeGridWeek: { pointer: true }
        },
        dayMaxEvents: true,
        nowIndicator: true,
        editable: false
    });

**Comment by vkurko** [comment]
Please see this [comment](https://github.com/vkurko/calendar/issues/113#issuecomment-1525673911).

**Comment by PedroYuriAlves** [comment]
Thanks, works just fine!  :)
