### ISSUE TITLE
buttonText option not Working

### ISSUE THREAD

**Issue by PedroYuriAlves** [vkurko/calendar#128]
The buttonText is not working, the text are show as undefined:

   buttonText: {
            today: 'Hoje',
            month: 'Mês',
            week: 'Semana',
            day: 'Dia',
            list: 'Lista'
        }
        
        
        
![calendar_buttonText](https://github.com/vkurko/calendar/assets/63973484/13264d38-e6d6-4d31-9540-eaf3b3db051c)

**Comment by vkurko** [comment]
You are using the wrong object field names. Take a look at the default object:
```js
{
  today: 'today',
  dayGridMonth: 'month',
  listDay: 'list',
  listWeek: 'list',
  listMonth: 'list',
  listYear: 'list',
  resourceTimeGridDay: 'day',
  resourceTimeGridWeek: 'week',
  timeGridDay: 'day',
  timeGridWeek: 'week'
}
```
So yours should be something like:
```js
{
  today: 'Hoje',
  dayGridMonth: 'Mês',
  timeGridWeek: 'Semana',
  timeGridDay: 'Dia',
  listWeek: 'Lista'
}
```

**Comment by vkurko** [comment]
I hope I can close this issue.
