### ISSUE TITLE
updating all events

### ISSUE THREAD

**Issue by hmzxpcm** [vkurko/calendar#129]
Please tell me how I can update all events. The component has methods of working with the event, but in my case, I need to update all the events without restarting the component (in order to save the scroll position). Updated events come from the server

**Comment by vkurko** [comment]
To load data into the calendar from the server, you need to use the [eventSources](https://github.com/vkurko/calendar#eventsources) option. Then, to reload the data, you can use the [refetchEvents](https://github.com/vkurko/calendar#refetchevents) method.
