### ISSUE TITLE
How can i get data from events: function

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#13]
I want to get events from this style:
events: {
    url: '', type: 'POST', cache: false,
    success: function(data) {
        var events = [];
        $(data).each(function(e, l) {
            $(l.events).each(function(c, d) {
                events.push({
                    id: d.id, start: d.start, end: d.end, title: d.title, className: l.className, textColor: l.textColor
                });
            });
        });
        return events;
    }
}

But i can't do this 
I can get eventSources function but i want to get this style from events
How can i do this.
My error log: Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by vkurko** [comment]
It looks like you need to use the [eventSources](https://github.com/vkurko/calendar#eventsources) option like this:

```js
eventSources: [{
    url: 'https://your-url-to-events.json',
    method: 'POST'
}]
```

**Comment by emrahnalci** [comment]
Thank you..
