### ISSUE TITLE
right click on event triggers dragging

### ISSUE THREAD

**Issue by mrvnklm** [vkurko/calendar#131]
performing a right click on an event activates the drag, is there a possibility to prevent that?
I want to right click to open the underlying href in a new tab or maybe even use the right click to open a context menu.

**Comment by vkurko** [comment]
Hi @mrvnklm  This needs to be fixed in the library itself. I'll try to do it when I have free time.

**Comment by mrvnklm** [comment]
Thank you!

**Comment by mrvnklm** [comment]
Working as expected, thanks a lot!
