### ISSUE TITLE
incorrect date click information

### ISSUE THREAD

**Issue by hmzxpcm** [vkurko/calendar#135]
if the grid starts at 9:20, the step is 30 minutes, then when you click at the end of the cell, for example, from 10:20 to 10:50, the callback returns date: 10:00, and if you click at the beginning of the cell, it returns 9:30.

https://github.com/vkurko/calendar/assets/71077983/6d2ec2c2-1e32-442b-8187-fbefa43a66f5

the video shows how an event is created when clicking on a cell, the date returned in this case is the start date of the event

**Comment by hmzxpcm** [comment]
unfortunately, I have not found how to solve this problem. And couldn't find an alternative to dateClick. I need an event to be created when clicking on a cell in it.

**Comment by vkurko** [comment]
Can you provide a live demo please? You can use this [template](https://jsbin.com/nademanuko/edit?js,output).

**Comment by hmzxpcm** [comment]
https://jsbin.com/yewuladuyi/1/edit?js,console,output

> Can you provide a live demo please? You can use this [template](https://jsbin.com/nademanuko/edit?js,output).

**Comment by hmzxpcm** [comment]
Uploading Запись экрана 2023-05-29 в 20.52.48.mov…

**Comment by vkurko** [comment]
Thank you for the demo. I confirm the issue. I'll try to provide a fix a.s.a.p.

**Comment by hmzxpcm** [comment]
it helped, thank you. You have a very good library, I think I will contact you more than once with feedback. :)
