### ISSUE TITLE
eventContent

### ISSUE THREAD

**Issue by tunaegilmez** [vkurko/calendar#136]
Hello sir. Why is this happening even though I added the css file?

<img width="393" alt="Screenshot 2023-05-29 at 22 44 50" src="https://github.com/vkurko/calendar/assets/93087643/7fce7672-22fa-485f-8b6d-b34973e0b06a">
<img width="1025" alt="Screenshot 2023-05-29 at 22 45 24" src="https://github.com/vkurko/calendar/assets/93087643/28d73fc1-f9cb-4c75-8b66-426d1901ee75">

**Comment by rameshKgisl** [comment]
Facing Same issue.

**Comment by vkurko** [comment]
To render HTML you need to return it as:

```js
return {html: "<div>some content</div>"};
```

**Comment by rameshKgisl** [comment]
Yes Got it. Please update them into README.

Thanks :)

**Comment by vkurko** [comment]
Can you clarify which words need to be corrected [here](https://github.com/vkurko/calendar#eventcontent)?
