### ISSUE TITLE
Choose Date

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#14]
How can i choose date and load items ?

**Comment by vkurko** [comment]
Hi @emrahnalci 

You need to implement date navigation yourself. As an example, you can refer to [Bookly's implementation](https://plugins.trac.wordpress.org/browser/bookly-responsive-appointment-booking-tool/tags/19.9.1/backend/modules/calendar/resources/js/calendar-common.js#L306) for this.

As soon as the date is changed, the Event Calendar will send a request to the URL specified in the  [eventSources](https://github.com/vkurko/calendar#eventsources) option.

**Comment by emrahnalci** [comment]
Thank you.
I will look and write feed back

**Comment by emrahnalci** [comment]
Hi @vkurko i tried this;

`
<html>
<body>


let dateSetFromDatePicker = false;
--
 
let calendar = new window.EventCalendar($container.get(0), $.extend(true, {}, settings, obj.options.calendar));
 
// Init date picker for fast navigation in Event Calendar.
$('.ec-toolbar .ec-title', $container).daterangepicker({
parentEl        : '.bookly-js-calendar',
singleDatePicker: true,
showDropdowns   : true,
autoUpdateInput : false,
locale          : obj.options.l10n.datePicker
}).on('apply.daterangepicker', function (ev, picker) {
dateSetFromDatePicker = true;
if (calendar.view.type !== 'timeGridDay' && calendar.view.type !== 'resourceTimeGridDay') {
calendar.setOption('highlightedDates', [picker.startDate.toDate()]);
}
calendar.setOption('date', picker.startDate.toDate());
});
 
// Export calendar
this.ec = calendar;


</body>
</html>`


than i tried datepicker onchange function and fullcalendar initialDate function but didn't work.

Can you write example code for me ?
When you at free time

**Comment by vkurko** [comment]
Hi @emrahnalci,

Here is an [example](https://jsbin.com/yulumizepa/edit?js,output). Click the date range in the calendar header and select a day from a different week.

**Comment by emrahnalci** [comment]
> Hi @emrahnalci,
> 
> Here is an [example](https://jsbin.com/yulumizepa/edit?js,output). Click the date range in the calendar header and select a day from a different week.

Thank youu Vladimir
I will try this 👍🏼
