### ISSUE TITLE
Can be time hidden for allDay events in dayGridMonth view?

### ISSUE THREAD

**Issue by dimakovalevskyi** [vkurko/calendar#143]
Hello, thanks for your library!

Can time be hidden for allDay events in `dayGridMonth` view? 

Can we get something like this
<img width="953" alt="image" src="https://github.com/vkurko/calendar/assets/20587172/59fccc54-c10e-4686-89b3-320680bfbded">

Instead of this
<img width="923" alt="image" src="https://github.com/vkurko/calendar/assets/20587172/0ca29ac9-455f-4f1c-865b-44fcfe79e0f8">

This could be solved manually if these events had a specific class on `ec-event` element like `ec-event-all-day`. But it doesn't have :
<img width="620" alt="image" src="https://github.com/vkurko/calendar/assets/20587172/10d3e91e-491e-4e85-aef3-b4be5535df29">

**Comment by vkurko** [comment]
Hello @dimakovalevskyi 

You can completely override event rendering using the [eventContent](https://github.com/vkurko/calendar#eventcontent) option. I've prepared a [demo](https://jsbin.com/daqoludemu/edit?js,output) for you.

In the future, it will be possible to add custom classes to events, so the method you suggested will also work.

**Comment by vkurko** [comment]
Actually I think that such a rendering option, when `div.ec-event-time` is missing for `allDay` events, I will make it default.

**Comment by dimakovalevskyi** [comment]
Yeah, thank you!
