### ISSUE TITLE
How to use view object

### ISSUE THREAD

**Issue by PHCPartsAlexis** [vkurko/calendar#144]
Hi All,

I've not got a lot of experience with JS so you'll have to forgive the rather n00b question, but how do I interact with the view object? I can't see any examples of how to do this, and all the things I've tried just result in the calendar not rendering!

I've tried this;
`<script type="text/javascript">
		let ec = new EventCalendar(document.getElementById('ec'), {
        view: 'resourceTimeGridWeek',
        height: '700px',
        headerToolbar: {
            start: '',
            center: 'title',
            end: ''
        },
        scrollTime: '07:00:00',
	currentStart='2023-6-12',
	firstDay: 1,`

(and obviously then supplying event data)

I've tried to do similar with views, naming a new view and supplying type, currentStart etc. to no avail.

This is the best calendar solution I've come accross btw, and vastly easier than some of my own home-brew efforts! Thanks to the dev's for the high quality package.

Cheers,

Alexis.

**Comment by PHCPartsAlexis** [comment]
Thanks for the prompt reply! I've got the calendar displaying, but what I am trying (and failing) is to convince the code to start at a given date, rather than displaying the current week.

I basically am building a room booking display system - so want to show "today" and the next 7 days for people to see availability.

So I looked for an option for this, but I could only find it under the view object and it's currentStart method. But I can't make it work.

**Comment by vkurko** [comment]
The currently displayed date is set by the [date](https://github.com/vkurko/calendar#date) option.

**Comment by PHCPartsAlexis** [comment]
Can you provide me an example of how I would use that option with a javascript date object please?

**Comment by vkurko** [comment]
[Here](https://jsbin.com/kirececeju/edit?js,output) the currently displayed date is January 7, 2024.

**Comment by PHCPartsAlexis** [comment]
Ah, thank you very much, that helps my understanding. However when using a week view, setting the date to any day within that week still only displays that week, not a week starting from the specified date which is what I'm trying to do :)

**Comment by vkurko** [comment]
Setting the correct value for `date` in combination with the correct value for `firstDay` will most likely get you the desired result :smile:

**Comment by PHCPartsAlexis** [comment]
Aha, bingo. Nice one :) Thanks for your help!
