### ISSUE TITLE
Duplicate calling eventSources.events function in dayGridMonth view

### ISSUE THREAD

**Issue by dimakovalevskyi** [vkurko/calendar#146]
Hello!

I use this code to load events dynamically via Ajax:
```
eventSources: [
  {events: loadEvents}
]
```

And when the calendar starts with `dayGridMonth` view, `loadEvents` function is called twice with different time ranges. This triggers two Ajax requests simultaneously after loading the page and executing js. 
<img width="882" alt="image" src="https://github.com/vkurko/calendar/assets/20587172/a457bdab-50dd-45b2-9809-a02a1b422744">

I think this is a bug. Can be this fixed?

I prepared [Demo](https://codepen.io/dimakovalevskyi/pen/ZEmbZJm) to show you.
<img width="1381" alt="image" src="https://github.com/vkurko/calendar/assets/20587172/397d1694-ba06-4829-9bf4-7891812e27a9">

**Comment by dimakovalevskyi** [comment]
> I confirm this is a bug. I'll try to fix it a.s.a.p.

Thank you a lot!

**Comment by vkurko** [comment]
This should be fixed in v1.4.1. Please check.

**Comment by dimakovalevskyi** [comment]
I confirm the bug is fixed. Thank you!
I will close issue.
