### ISSUE TITLE
Resize events

### ISSUE THREAD

**Issue by wvffle** [vkurko/calendar#15]
https://github.com/vkurko/calendar#editable speaks of resizing events though it's not yet implemented.

**Comment by vkurko** [comment]
Hi @wvffle,

You are right, the resizing is not implemented in Event Calendar. Let me assume that this will be the next feature I will implement when I have some free time :smiley:

**Comment by wvffle** [comment]
Great, I'm looking forward to it.

If you're not planning on getting that done anytime soon, I could make a PR, though you'd need to point me to the package that I should modify

**Comment by vkurko** [comment]
Well, to accept PRs, I would have to first draw up some code style rules... Which again takes time :smile: So let's try without them for now. You need to modify the `Interaction` plugin/package.

**Comment by wvffle** [comment]
Unfortunately, it turned out that I won't have spare time anytime soon to work on it ;/

**Comment by JuniorJPDJ** [comment]
Is anyone working on this maybe?

**Comment by vkurko** [comment]
> Is anyone working on this maybe?

At the moment, no.

**Comment by mlscherer** [comment]
Hello @vkurko , just found this projetct and is almost everything I was looking for. Great job!

The resize event option is the only thing missing for now... Any updates on that? Or at least anything planned for the future?

Thanks!

**Comment by vkurko** [comment]
Hi @mlscherer 

Thanks for your interest in Event Calendar. I'll try to work on `resizing` in the coming weeks.

**Comment by mlscherer** [comment]
> Hi @mlscherer
> 
> Thanks for your interest in Event Calendar. I'll try to work on `resizing` in the coming weeks.

Hey, that's great, I hope it works out.

Another thing that's relative to this... Do you plan on making it possible to create events with the "click and drag", like Google Calendar does? So users can create an event and automatically define the period in the same action?

Thanks

**Comment by vkurko** [comment]
> Another thing that's relative to this... Do you plan on making it possible to create events with the "click and drag", like Google Calendar does? So users can create an event and automatically define the period in the same action?

This is called `select` in FullCalendar's terms. There is an open [issue](https://github.com/vkurko/calendar/issues/8) about it. You can vote for this to be further developed :smile:.

**Comment by vkurko** [comment]
Hi all.

Sorry it took long. Please check out v0.10.0 which contains the ability to resize events. There are new options [eventDurationEditable](https://github.com/vkurko/calendar#eventdurationeditable), [eventResizeStart](https://github.com/vkurko/calendar#eventresizestart), [eventResizeStop](https://github.com/vkurko/calendar#eventresizestop), [eventResize](https://github.com/vkurko/calendar#eventresize).

Let me know if there are any issues :smile:
