### ISSUE TITLE
Preventing Event Overlap

### ISSUE THREAD

**Issue by csonic656** [vkurko/calendar#150]
I really like this calendar, but I have a particularly specific use case for it. I was wondering if it would be possible to prevent events from overlapping, or perhaps once overlapped, combine the two events, particularly in the timeGridWeek view? Also, would it be possible to prevent events from being drag created into multiple days?

**Comment by vkurko** [comment]
If I understand you correctly, then overlapping events shouldn't happen during dragging? The only way to control this in your case is to use the [eventDrop](https://github.com/vkurko/calendar#eventdrop) hook. Inside the hook, you can check if the conditions are met and then cancel the drag by calling the `revert` method.

**Comment by vkurko** [comment]
I hope I can close this issue.
