### ISSUE TITLE
Could you add a method?

### ISSUE THREAD

**Issue by pavelshikin** [vkurko/calendar#151]
We need a method that will help us choose a period (favorites) . Returns an information object with data, as if the dateClick event was triggered for this point.

**Comment by vkurko** [comment]
Have you looked at the [dateFromPoint](https://github.com/vkurko/calendar#datefrompoint-x-y-) method? Also [select](https://github.com/vkurko/calendar#select) is available for periods selection.

**Comment by vkurko** [comment]
I hope I can close this issue.

**Comment by pavelshikin** [comment]
Yes, thank you, the problem is partially solved. Of course, I would like the first click on the point to mean the beginning of the selection, and the second click to mean the end of the selection, and the period is highlighted as well as with SELECT
