### ISSUE TITLE
Vertical Resources and Daily Events in Event Calendar Component

### ISSUE THREAD

**Issue by bedeleu** [vkurko/calendar#153]
Hi @vkurko,
Firstly, I want to express my gratitude for creating such an excellent component.
I have a query regarding customization possibilities for the Event Calendar. Specifically, I'm interested in achieving a similar look to the attached screenshot. Is it possible to modify the component to display resources in a vertical manner, along with daily events?
Thank you for your time and assistance.
Best regards,
Alex

![image](https://github.com/vkurko/calendar/assets/31882188/99ac712f-a7df-4ae1-aa0c-543718f8ef7d)

**Comment by vkurko** [comment]
Please see issue #30. I will close this ticket in favor of an already open one.
