### ISSUE TITLE
Is there a way to change 'timeGridWeek' to show more days then a week? Example 10-15? 

### ISSUE THREAD

**Issue by cmjoseph07** [vkurko/calendar#157]
Firstly, I would like to express my appreciation for your excellent library. It's been a great resource and I'm grateful for the opportunity to utilize it.

I am writing to understand the 'timeGridWeek' that displays a span of 7 days, which is indeed useful. However, for my specific use case, it would be beneficial to have an extended view that encompasses two weeks at a time for example.

If it's not feasible to directly modify the week view, perhaps there could be an alternative solution. For instance, is there a way to customize a different view and import it into the views section? This flexibility would greatly enhance the functionality of the calendar for users who need a broader overview of their schedule.

Thank you for considering this request in advance!

**Comment by vkurko** [comment]
Hi @cmjoseph07

Is [duration](https://github.com/vkurko/calendar#duration) what you are looking for?

**Comment by cmjoseph07** [comment]
@vkurko 

Yes! This is exactly what I was looking for. Sorry to trouble you on this and I again appreciate it!!
