### ISSUE TITLE
Custom Button in Header / Footer

### ISSUE THREAD

**Issue by vasandharaj** [vkurko/calendar#159]
Is it possible to include custom button in header / footer as in FullCalendar ??

**Comment by vkurko** [comment]
Most likely you mean the [customButtons](https://fullcalendar.io/docs/customButtons) setting for FullCalendar. Unfortunately, it is currently missing in the Event Calendar.

**Comment by vasandharaj** [comment]
@vkurko Thanks for the quick reply.  Yes. Will it be available in near future ?

**Comment by vkurko** [comment]
I will try to implement it in one of the next releases.

**Comment by vkurko** [comment]
Thanks to @Nicholas-Toh the [customButtons](https://github.com/vkurko/calendar?tab=readme-ov-file#custombuttons) option is now available in Event Calendar v2.7.0.
