### ISSUE TITLE
A11y warning after updating to svelte 4.x

### ISSUE THREAD

**Issue by cmjoseph07** [vkurko/calendar#160]
Svelte 4.x now have various A11y warnings that get displayed in dev mode. Is there a way you could look into fixing these A11y issues so the warnings will go away. Examples below: 

https://svelte.dev/docs/accessibility-warnings

`1:19:43 PM [vite-plugin-svelte] /node_modules/@event-calendar/time-grid/src/Event.svelte:100:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.`
`1:19:43 PM [vite-plugin-svelte] /node_modules/@event-calendar/time-grid/src/Event.svelte:100:0 A11y: <div> with click, mouseenter, mouseleave handlers must have an ARIA role`
`1:19:43 PM [vite-plugin-svelte] /node_modules/@event-calendar/core/src/Buttons.svelte:29:4 Empty block`
`1:19:43 PM [vite-plugin-svelte] /node_modules/@event-calendar/time-grid/src/all-day/Event.svelte:95:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.`
`1:19:43 PM [vite-plugin-svelte] /node_modules/@event-calendar/time-grid/src/all-day/Event.svelte:95:0 A11y: <div> with click, mouseenter, mouseleave handlers must have an ARIA role`

**Comment by vkurko** [comment]
@cmjoseph07 Thanks, I'll look into this issue.

**Comment by vkurko** [comment]
@cmjoseph07 

These warnings should be fixed/suppressed in version 1.5.1. Please check.

**Comment by cmjoseph07** [comment]
@vkurko 

✅ These warnings have been fixed/suppressed in 1.5.1, closing issue.
