### ISSUE TITLE
Change the background & text colors of css to make a custom pallet?

### ISSUE THREAD

**Issue by SuperPauly** [vkurko/calendar#165]
I wa trying to find a Dark Mode but all my attempts have failed.

What would I need to do to activate dark mode, is this possible?

I had a quick look at the code for core especially the scss and it don't seme like it.

Is this planned?

**Comment by vkurko** [comment]
There is already an open [issue](https://github.com/vkurko/calendar/issues/68) about the dark theme. I'll close this one in favor of the one already open.

There, someone was going to implement the necessary changes to the CSS, but I haven't seen the results yet.
