### ISSUE TITLE
Add Quarter View

### ISSUE THREAD

**Issue by jnegron357** [vkurko/calendar#167]
It would be great to have a **Quarter view** to the calendar. This feature would help users with quarterly reports and analytics. Idealy, we'd see a box for each quarter then it would be divided into three boxes for each month in the quarter. Within those we'd see some form of icon or indicator of events for that month. Clicking on the month will show a modal dialog with more details on the events for that month. This would be a useful tool for small to mid-size companies that manage or create events.

**Comment by vkurko** [comment]
I'm not sure if such a view should be built into the library. Do you have examples with other calendars, preferably FullCalendar?

**Comment by vkurko** [comment]
I hope I can close this issue.
