### ISSUE TITLE
No cut events | Fix height with content & duration

### ISSUE THREAD

**Issue by parismst** [vkurko/calendar#168]
Hello,

Thank you very much for providing us with the best calendar.
I meant to ask is it possible not to cut the event, so to get the right height of the content along with the duration?

![image](https://github.com/vkurko/calendar/assets/40799825/b539b699-8890-4d34-a093-b7f2d53a529f)

Thanks

**Comment by vkurko** [comment]
The height of each event corresponds to its duration. If you want the height to adjust to the content inside the events, then try adding the CSS rule

```css
.ec-event {
    height: auto!important;
}
```

**Comment by parismst** [comment]
I've tried it, it doesn't work like that.
Is there a way to display every half hour on the left side of the bar instead of an hour?
Also, we have possibility to have the format 24 hours and not 12 hours?

**Comment by vkurko** [comment]
Please check [slotDuration](https://github.com/vkurko/calendar#slotduration) and [slotLabelFormat](https://github.com/vkurko/calendar#slotlabelformat) options.

**Comment by parismst** [comment]
I hadn't noticed that.
Thanks :)
