### ISSUE TITLE
refetchEvents problem

### ISSUE THREAD

**Issue by hmzxpcm** [vkurko/calendar#171]
I am trying to add an event in a second and call refetchEvents, but the calendar is not updated. Tell me what I'm doing wrong?

https://jsbin.com/liluceviba/edit?js,console,output

**Comment by vkurko** [comment]
[refetchEvents](https://github.com/vkurko/calendar#refetchevents) only works in conjunction with [eventSources](https://github.com/vkurko/calendar#eventsources). In your case, try using the [addEvent](https://github.com/vkurko/calendar#addevent-event-) method.

**Comment by hmzxpcm** [comment]
in my case, I need to update a lot of events, EventSource judging by the description does not suit me, there is a chance that you add a method to update all events

**Comment by vkurko** [comment]
Ok. What about `ec.setOption('events', newEventsArray)`?
