### ISSUE TITLE
Can't add html in dayHeaderFormat?

### ISSUE THREAD

**Issue by cipriano200** [vkurko/calendar#173]
Cant add html inside dayHeaderFormat function
```
dayHeaderFormat: function(date) {
  return '<div class="wpfs-calendar-week-day-cell">Some text</div>';
}
```

**Comment by vkurko** [comment]
In v2.0.0 it is now possible to return HTML like this:

```js
dayHeaderFormat: function(date) {
  return {html: '<div class="wpfs-calendar-week-day-cell">Some text</div>'};
}
```

**Comment by cipriano200** [comment]
Thank you for your answer.

One more question if you dont mind:
Is it possible to add html after header toolbar?

**Comment by vkurko** [comment]
The [titleFormat](https://github.com/vkurko/calendar#titleformat) in v2.0.0 also supports passing html from a function. There are no other options yet. In the future, the setting for [Custom buttons](https://github.com/vkurko/calendar/issues/159) will most likely suit you.

**Comment by vkurko** [comment]
I hope I can close this issue.

**Comment by cipriano200** [comment]
Thank you for the release
