### ISSUE TITLE
different time grid step

### ISSUE THREAD

**Issue by hmzxpcm** [vkurko/calendar#174]
Please help me, I need to set a different grid step, for example 9:00, 9:10, 9:30, 10:10. But I didn't find it in the documentation, is there any possible solution to this problem?

**Comment by vkurko** [comment]
The time step is set by the [duration](https://github.com/vkurko/calendar#duration) option. But this step is constant throughout the day.

**Comment by hmzxpcm** [comment]
is there a chance that you will add this to your calendar?
