### ISSUE TITLE
Is it possible to get current view inside dayHeaderFormat in v2?

### ISSUE THREAD

**Issue by cipriano200** [vkurko/calendar#175]
dayHeaderFormat should have view variable as second parameter?

```
dayHeaderFormat: function(date, view) {

}
```

**Comment by vkurko** [comment]
What about [getOption('view')](https://github.com/vkurko/calendar#getoption-name-) or [getView()](https://github.com/vkurko/calendar#getview) methods?

**Comment by cipriano200** [comment]
I tried this:
```
				dayHeaderFormat: function(date) {
					console.log( calendar.getview() );
				}
```

But is not working: Uncaught TypeError: Cannot read properties of undefined (reading 'getview')

**Comment by vkurko** [comment]
Indeed, the `calendar` is not yet defined at the time of the first call to the function. But you can add an `if` and you know which view is initially active:

```js
let calendar;
calendar = new EventCalendar(document.getElementById('ec'), {
    view: 'timeGridWeek',
    dayHeaderFormat: function(date) {
        if (!calendar || calendar.getView().type == 'timeGridWeek') {
            // timeGridWeek
        } else if (calendar.getView().type == 'timeGridDay') {
            // timeGridDay
        } else {
            // and so on...
        }
    }
};
```

**Comment by cipriano200** [comment]
Works! Thank your for the help.
I have replaced FullCalendar with your library.
