### ISSUE TITLE
date labels as hyperlinks

### ISSUE THREAD

**Issue by piotrm73** [vkurko/calendar#176]
hi
I don't see a method to move calendar to a specific day...
date label shouldn't be an active hyperlinks like in fullcalendar?

**Comment by vkurko** [comment]
To go to a specific date, you need to set it with [setOption('date', newDate)](https://github.com/vkurko/calendar#setoption-name-value-).



> date label shouldn't be an active hyperlinks like in fullcalendar?

Currently they are not in the Event Calendar.

**Comment by piotrm73** [comment]
oh ok. didn't notice it.. it's working thanks!
