### ISSUE TITLE
unique classes in views

### ISSUE THREAD

**Issue by piotrm73** [vkurko/calendar#177]
I have suggestion to give unique classes in views, because now timeGridDay, timeGridWeek and resourceTimeGridWeek all are in '.ec-week' container nad this makes it difficult to customize views in css...
for example I have many resources in resourceTimeGridWeek and I had to change some css there but it spoils the timeGridDay and timeGridWeek views

**Comment by piotrm73** [comment]
ok. I installed latest version and fortunatelly it's working on older nodejs...but I have just one more suggestion about resource view

![image](https://github.com/vkurko/calendar/assets/23495580/8e460ee5-4b7b-4152-aaf7-74f615708a76)

it would be good to separate .toolbar from the rest (.ec-header, .ece-all-day, ec-body) because when it's many resources you must use oferflow:auto or scroll, and it would be good to attach overflow to container with just resources data, and toolbar should not be scrolled then

**Comment by vkurko** [comment]
Thanks for the suggestion. For a large number of resources, this [view](https://github.com/vkurko/calendar/issues/30) would be more suitable. Hope it gets implemented someday.
