### ISSUE TITLE
[Feature request] Add option to add thumbnails to events

### ISSUE THREAD

**Issue by TentacleSama4254** [vkurko/calendar#18]

**Comment by vkurko** [comment]
Hi @TentacleSama4254 

Can you provide more details about the requested feature please?

You currently have full control over the content displayed inside the event using the [eventContent](https://github.com/vkurko/calendar#eventcontent) option. Perhaps this option will suit your needs.

**Comment by TentacleSama4254** [comment]
> Hi @TentacleSama4254 
> 
> Can you provide more details about the requested feature please?
> 
> You currently have full control over the content displayed inside the event using the [eventContent](https://github.com/vkurko/calendar#eventcontent) option. Perhaps this option will suit your needs.

Oh sorry my bad, thx
