### ISSUE TITLE
strange behaviuor with dayMaxEvents

### ISSUE THREAD

**Issue by piotrm73** [vkurko/calendar#182]
as you can see, there are days with just one event, but it's not in the DOM, instead link "show more" appears
![image](https://github.com/vkurko/calendar/assets/23495580/ec5af055-13db-4e15-a044-33760258a6fa)

**Comment by vkurko** [comment]
Can it be a multi-day event?

**Comment by piotrm73** [comment]
yep it is

**Comment by vkurko** [comment]
Then I guess this multi-day event starts let's say on 6 (czw.) and it is hidden there. That's why it is also hidden on 7, 8 and 9. I see no bug here.

**Comment by piotrm73** [comment]
maybe it's no bug, but it looks strange :) anyway, I realize this may be difficult to improve

**Comment by vkurko** [comment]
If you have ideas on how this can be improved, I'm ready to consider them :smile:

**Comment by vkurko** [comment]
Just checked Google Calendar and it has the same behavior. So I'm closing this ticket for now.
