### ISSUE TITLE
Unable to get dateClick and noEventsClick

### ISSUE THREAD

**Issue by tatianavazquezvl** [vkurko/calendar#183]
Hello!

I have a problem with these two methods, my goal is to click on a day and create a new event. I am using Svelte. 
I added the "dateClick" event to the options, and put just a simple console.log of the info and it is not showing when I click on a day or even an event. Same thing happens with the noEventsClick method. I also tried to change a variable inside the two functions, and console log it to check if it changed, and again nothing.

Lastly, I checked that there's an option to add 'noEventsContent', I tried that out and the text or html I put there didn't show in the days with no events.

Here's my code:

https://svelte.dev/repl/1ab8b57e55244904bb3b2a9778ba9d89?version=4.2.1

Here's a demo:

https://github.com/vkurko/calendar/assets/143443292/c1e741e1-ed12-438b-b059-43e4701f622c

Thank you so much for reading :)

**Comment by vkurko** [comment]
Hello,

Since v1.0.0 the [dateClick](https://github.com/vkurko/calendar#dateclick) option requires the `Interaction` plugin. It is mentioned in the documentation.

**Comment by vkurko** [comment]
[noEventsContent](https://github.com/vkurko/calendar#noeventscontent) only applies to the `list` views, not `dayGrid`.

**Comment by vkurko** [comment]
I hope I can close this issue.
