### ISSUE TITLE
Trouble using event-calendar in ASP NET

### ISSUE THREAD

**Issue by sajpy** [vkurko/calendar#185]
Hey there! I've gone through the documentation but still am unsuccessful in using your calendar. What I need the most is the resource view.
I've been trying to include the library in my ASP.NET Core project, through npm as well as through Library Manager, both failed.
Most recently I've been getting error: ```Uncaught TypeError: Failed to resolve module specifier "svelte/internal". Relative references must start with either "/", "./", or `"../".```, which comes from `event-calendar/core/index.min.js`

Is there any way, that you know of, to get rid of these problems with dependencies? 
Or is there a way to use the [pre-built-browser-ready-bundle](https://github.com/vkurko/calendar#pre-built-browser-ready-bundle) but together with resource view/plugin in my project? (because this was the only way I could render the calendar, but was missing the resource plugin)

**Comment by vkurko** [comment]
Hello,

1. Unfortunately, I lack information on how I can reproduce the problem. Maybe you can create a project demonstrating the problem in [StackBlitz](https://stackblitz.com/)? I'd also like to point out that the current version of the `@event-calendar/core` package [does not have](https://www.npmjs.com/package/@event-calendar/core?activeTab=code) an `index.min.js file`.
2. The pre-built version includes all plugins, so the resources view should be available.

**Comment by vkurko** [comment]
Please reopen the ticket if you have more details.
