### ISSUE TITLE
Different resource view for week

### ISSUE THREAD

**Issue by paubikas** [vkurko/calendar#19]
Is it possible to change view for resourceTimeGridWeek to show Day as header instead resource and then split to resource:

![image](https://user-images.githubusercontent.com/83951420/130043372-1a45502a-345c-4342-9bed-fe0432f7bc03.png)

**Comment by vkurko** [comment]
Hi @paubikas 

The new version `0.3.0` of the Event c\Calendar has a new option [datesAboveResources](https://github.com/vkurko/calendar#datesaboveresources)  that implements the requested layout.
