### ISSUE TITLE
Drag and drop ;) ?

### ISSUE THREAD

**Issue by dux** [vkurko/calendar#2]
For calendar entries, to reschedule, any plans?

**Comment by vkurko** [comment]
Hi @dux, I think I'll do it.

**Comment by vkurko** [comment]
Drag-and-drop on desktop is now available in version `0.1.0-beta.1`.

See [demo](https://vkurko.github.io/calendar/) and check out the docs for [eventStartEdiatble](https://github.com/vkurko/calendar#eventstarteditable), [eventDragStart](https://github.com/vkurko/calendar#eventdragstart), [eventDragStop](https://github.com/vkurko/calendar#eventdragstop), [eventDrop](https://github.com/vkurko/calendar#eventdrop) and [dragScroll](https://github.com/vkurko/calendar#dragScroll).

**Comment by dux** [comment]
king! thx :)

**Comment by vkurko** [comment]
I'm closing this issue. New feedback/ideas are welcomed.
