### ISSUE TITLE
Today button not being called on .ec-button class

### ISSUE THREAD

**Issue by steveb85** [vkurko/calendar#201]
Adding a function on event listener for .ec-button works for all buttons except the today button, which seems to go into disabled before the event listener receives it. 

Haven’t been able to find any work around and have had to remove the button for now! 

Otherwise loving it, thanks

**Comment by vkurko** [comment]
With event delegation it [works](https://jsfiddle.net/219cwrze/):

```js
const el = document.getElementById('ec');
const ec = new EventCalendar(el, {
  view: 'timeGridWeek'
});

el.addEventListener('click', function (e) {
  console.log(el.contains(e.target.closest('.ec-button')));
});
```
