### ISSUE TITLE
AddEvent About

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#21]
Hi Vladimir,
I have a new question.
I'm adding new event calendar but im refreshing after adding event.
I wont reload the page.

My question: How can i add event on calendar ? 
I want it to add a new event (or delete event) when I press the button than i will import my project :)
How can i do this?
I'm looking "addEvent( event )" but i didn't it.

**Comment by vkurko** [comment]
Hi @emrahnalci 

Sorry, I'm not sure I understood your question correctly. If you need to add an event to the calendar you can use either [addEvent](https://github.com/vkurko/calendar#addevent-event-), or [refetchEvents](https://github.com/vkurko/calendar#refetchevents) if the new event is stored in the database and can be loaded from the server.
