### ISSUE TITLE
dayMonthGrid not working when events added

### ISSUE THREAD

**Issue by maotcha** [vkurko/calendar#212]
Hi! The month display works fine if I don't have any events, but once I add one, it no longer shows and I'm unable to toggle back to the other views (same issue with list view). My code mostly comes from the demo/examples in the README, but I don't use the provided CSS. Could this be the issue? Any help would be appreciated, thanks!

**Comment by amoscicki** [comment]
hi,
I started works on porting the calendar to the tailwind and it seems that some classes are required for some of the functions to work. 
I don't think you need to have same CSS and I'm still deep in (just didn't have much time for this recently) to establish exact which classes with which exact settings are required for things to keep working.
Are you still applying all the ec-* classes to the elements or are you  replacing any of these?
If you use the original CSS does it work? As the issue may also be somewhere else

**Comment by maotcha** [comment]
I've tried applying the original CSS, but I'm not sure if I'm doing it right. As of now, I import '@event-calendar/core/index.css' after I import Calendar, TimeGrid, DayGrid, etc (I'm using Svelte if that makes a difference). I'm also not sure how to apply all the ec-* classes. Sorry for the general lack of competency, I'm new to all of this.

**Comment by vkurko** [comment]
> but once I add one, it no longer shows

Can you provide some sample code so I can reproduce the issue?

**Comment by vkurko** [comment]
> Can you provide some sample code so I can reproduce the issue?

@maotcha, any update on this?

**Comment by maotcha** [comment]
I figured it out, just had to reinstall the core package. Thanks for your help!
