### ISSUE TITLE
Can't  import event calendar

### ISSUE THREAD

**Issue by alka7ex** [vkurko/calendar#214]
Hi Team
I would like to ask some help or advise, i was got an error where i try to setup the @event-calendar for my project here is the error

<img width="679" alt="Code_isOb0doPAh" src="https://github.com/vkurko/calendar/assets/18338838/f1623500-b34b-48c4-9e7d-8218c49ff72f">

Could not find a declaration file for module '@event-calendar/day-grid'. '/home/haikal/grorental/svelte/p2/project1/node_modules/@event-calendar/day-grid/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/event-calendar__day-grid` if it exists or add a new declaration (.d.ts) file containing `declare module '@event-calendar/day-grid';`ts(7016)

**Comment by vkurko** [comment]
Instead of `import type` you should use just `import`:

```js
import Calendar from '@event-calendar/core';
import TimeGrid from '@event-calendar/time-grid';
```

**Comment by alka7ex** [comment]
Hi @vkurko 
Thank you for your response, i actually was trying it also but i had different error now here is the screenshot.
<img width="680" alt="XnauBxyxBZ" src="https://github.com/vkurko/calendar/assets/18338838/d1db6d9e-6105-47af-a3d0-8cce80d47d5e">
<img width="679" alt="QSDMLWe2oj" src="https://github.com/vkurko/calendar/assets/18338838/0e1c3df0-56ac-4ce4-95f1-3c6ef31035ca">
<img width="960" alt="brave_KL6Kbmafc4" src="https://github.com/vkurko/calendar/assets/18338838/04064f57-162c-418e-bc32-123703196103">

**Comment by vkurko** [comment]
Did you `npm install --save-dev @event-calendar/time-grid`?

**Comment by alka7ex** [comment]
Yes, i already install it, here is my npm list
![image](https://github.com/vkurko/calendar/assets/18338838/8c1d79fc-0c5f-424b-8087-1c619ea81bc8)

**Comment by vkurko** [comment]
There is really no support for TypeScript right now, that is, there is _declaration file_. But this should not prevent you from using the library in TypeScript.

The error indicates that for some reason the `@event-calendar/time-grid` package is not available. I have no idea yet why this is happening for you.

**Comment by alka7ex** [comment]
Hi @vkurko 
some how it's works now but yes it still complaining about typescript, i believe it should be works from the start, but i was distracted by the types complain, and didn't check it properly, sorry about it. and thank you for willing to answer my questions

![image](https://github.com/vkurko/calendar/assets/18338838/135ceac2-e372-46ed-b27a-881b777b88b1)
![image](https://github.com/vkurko/calendar/assets/18338838/5da0234b-5842-43fc-853b-d205c5f14002)
![image](https://github.com/vkurko/calendar/assets/18338838/764a2d0d-0482-4579-b323-5c15f79e8fed)
