### ISSUE TITLE
Is is possible to lock the nowindicator to UTC or diffrent timezone?

### ISSUE THREAD

**Issue by tbbw** [vkurko/calendar#215]
Is it possible to lock the nowIndicator after a diffrent timezone than the browsers own timezone?

Example of use cases would be if i travel abroad or we as a team stick with a UTC timezone if we work in diffrent timezones?
Since 5pm "here" is not 5pm "there" kind of thing.

**Comment by vkurko** [comment]
Hello,

Event Calendar does not currently support any time zones. Namely, a setting indicating the time zone would be useful in this case. FullCalendar also has a `now` setting, which is [considered by some users](https://github.com/fullcalendar/fullcalendar/issues/5753) to be a setting that should also affect the position of the now indicator. Perhaps the Event Calendar needs to implement exactly this behavior.

**Comment by tbbw** [comment]
Interesting so i'm not the only one that wished this was a thing.

My thought was if the nowindicator had a timezone option where if it's unset it defaults to the browsers timezone like it is now but if it's set you can specify a spesific timezone that you wish it would use.
This way it would not break compability with something people already made and in use.

**Comment by vkurko** [comment]
Yes, the time zone setting is, in my opinion, the most suitable option for this case. This [timeZone](https://fullcalendar.io/docs/timeZone) option is available in FullCalendar. Perhaps the time has come to implement it in the Event Calendar and initially so that it affects only the now indicator.

**Comment by tbbw** [comment]
Is this on the roadmap or still in it needs more thought?

**Comment by vkurko** [comment]
Unfortunately, there is no roadmap yet. I haven't been able to devote enough time to the project in recent months. I hope to have that time in the coming months and implement some new features.

**Comment by orionnelson** [comment]
@vkurko  The UTC thing is a bit of a pain leads to shady code like this where I have to adjust around the adjustments  I made for drag and drop

![image](https://github.com/user-attachments/assets/a3822202-043b-4b8c-8fb5-d160e099ffb5)


If I code my methods to convert to EDT I need to to do the conversion for other ec methods it leads to strange code


https://github.com/user-attachments/assets/f31c1e3d-1f96-4722-b474-aaa0bb8df61b

**Comment by vkurko** [comment]
> @vkurko The UTC thing is a bit of a pain leads to shady code like this where I have to adjust around the adjustments I made for drag and drop
> 
> ![image](https://private-user-images.githubusercontent.com/44347765/374386831-a3822202-043b-4b8c-8fb5-d160e099ffb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTY4NjcsIm5iZiI6MTcyODM5NjU2NywicGF0aCI6Ii80NDM0Nzc2NS8zNzQzODY4MzEtYTM4MjIyMDItMDQzYi00YjhjLThmYjUtZDE2MGUwOTlmZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE0MDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NmMxMjFhMWY5MDdlZjY0YWU1OGIwMDc4NmE0ZWI3M2QwZjdjNTc1YTBhZjU5NGM3MTIwNWYzOWQ4MTg2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.auZs5kYdnG5eHSqvXraj_qNOXwduqbDXYYu2KW4eEGE)
> 
> If I code my methods to convert to EDT I need to to do the conversion for other ec methods it leads to strange code
> 
>  2024-10-07.21-54-56.mp4

Sorry, I'm not quite clear what this has to do with `nowIndicator`. Anyway, all calendar hooks and methods operate on dates in your local time zone, not UTC. Can you explain why you add and subtract 4 hours each time?

**Comment by tbbw** [comment]
Is 5PM in russia the same time as 5pm in north america?
In some countries there are more than one timezone.
Because the calendar blindly trust the visitors own timezone and cannot be told to stick with a spesific timezone ( i.e UTC, PST, GMT... daylight savings ) if i schedule a zoom meeting at 5pm in one timezone you will see that as 5pm in your timezone which is not the same time.

Because i cannot tell the calendar what timezone it uses you end up with shenanigans like adding and subtracting hours like shown in the example above.
The nowindicator is just one of the problems with not been able to lock the timezone of the calendar.

I understand that if you only use the calendar for use in your own timezone and all parties that visit the calendar use the same timezone as you then it would not be an issue, the problem happens when you mix in other people from other areas of the planet.

Most people stick with UTC to get around with "5pm my time... or 5pm your time?" problem but locking it to "5pm in my timezone" would also be useful if you only cared about the local timezone of what ever country your project resides in.

**Comment by vkurko** [comment]
> if i schedule a zoom meeting at 5pm in one timezone you will see that as 5pm in your timezone

I don't think the lack of time zone support prevents you from displaying events correctly for a user in another time zone. If you know their time zone, you can easily prepare the correct data on the server. The main consumer of the Event Calendar, the Bookly plugin with tens of thousands of installations, copes with this task perfectly.

The `nowIndicator` really can't work any other way now. And to fix it, we really need to make timezone support at least for it. If anyone wants to help with this task, please make a PR, I will review it in priority order.

**Comment by tbbw** [comment]
Yes alot of people have had to McGyver the events on the serverside cause the calendar trust the timezone of the browser blindly... it's still server side shenanigans :)
The nowIndicator could fix the "5pm my time or 5pm your time" comfusion especially if you work towards a diffrent timezone than your own.

**Comment by vkurko** [comment]
> Yes alot of people have had to McGyver the events on the serverside cause the calendar trust the timezone of the browser blindly...

...because support for modern API for working with dates and time zones in JS is weak.

I hope you store your users' time zone as a named string to support daylight savings. But JS doesn't support named time zones yet. Yes, there are third-party libraries for this, but I won't embed a third-party library into the calendar. Instead you can use such libraries in your project. Fortunately, the calendar provides you with all the options/callbacks for this.

Again, I think it is not the calendar's problem that you cannot display data in the correct time zone. As for `nowIndicator`, I agree that there is currently no solution to shift it.

**Comment by tbbw** [comment]
> ...because support for modern API for working with dates and time zones in JS is weak.

> But JS doesn't support named time zones yet. Yes, there are third-party libraries for this, but I won't embed a third-party library into the calendar.

*facepalm*

**Comment by tbbw** [comment]
I get it, not a feature you personally cannot see a use for.
So only alternative is fullcalendar which has added support for more than one timezone or to be locked to spesific timezone both for the calander itself and the nowindicator can be set to any time/timezone.
