### ISSUE TITLE
Header day widths wrong in initial load

### ISSUE THREAD

**Issue by ile** [vkurko/calendar#216]
Using the latest ES6 module. Made some color changes in CSS (don't affect box sizes).

When I initially load the page, the day widths in the headers are a bit too big:

![image](https://github.com/vkurko/calendar/assets/433707/fe2480b3-6947-48d3-97cf-8326cb45bf8a)

When I resize the browser, they are corrected:

![image](https://github.com/vkurko/calendar/assets/433707/482b103d-d161-49c1-a5cb-fe2cd01770ad)

Initial width: 

![image](https://github.com/vkurko/calendar/assets/433707/63a2b44c-302a-49d3-b941-ec4f7a61a0a9)

Resized:

![image](https://github.com/vkurko/calendar/assets/433707/fea5b066-f44e-46a2-a303-7bdb921a4656)

**Comment by vkurko** [comment]
Can you please provide the set of options you use to initialize your calendar so I can reproduce the problem?

**Comment by ile** [comment]
Sorry, I should have included them.

And looking at them, seems like this is the reason:

`height: '80vh',`

Full code:

```js
		new Calendar({
			target: this.calendar,
			props: {
				plugins: [TimeGrid, Interaction],
				options: {
					height: '80vh',
					allDaySlot: false,
					editable: true,
					view: 'timeGridWeek'
				}
			}
		});
```

**Comment by vkurko** [comment]
I have prepared a [demo](https://jsbin.com/xokirebiro/edit?html,output) with your options and cannot reproduce the issue. Do you see the problem with this demo?

**Comment by ile** [comment]
Not in the link, but I can try to make a demo myself, will take a day though (some other things to do).

**Comment by vkurko** [comment]
> I can try to make a demo myself

Thank you, this will be very helpful.

**Comment by ile** [comment]
I don't have a reproducible link yet, but I noticed that the problem happens when there is no `ec-with-scroll` class in the calendar wrapper. And in my case it is not there in the start for some reason. 

When I resize the window, it appears there and the problem is fixed. But initially that classname isn't there and the problem happens.

**Comment by vkurko** [comment]
Yes, this class is set automatically depending on the presence of scrollbar in the main section.  It's not clear why this doesn't work in your case.

**Comment by ile** [comment]
One thing that may affect it - I had to use a dynamic import to import the packages (because I'm using this from a commonjs package):

```
let Calendar, TimeGrid, Interaction;

import("@event-calendar/core").then((core) => {
	Calendar = core.default;
});

import("@event-calendar/time-grid").then((timegrid) => {
	TimeGrid = timegrid.default;
});
import("@event-calendar/interaction").then((interaction) => {
	Interaction = interaction.default;
});
```

**Comment by ile** [comment]
Maybe not that easy. I will try to make a repo for the demo.

**Comment by ile** [comment]
I was looking at the compiled Svelte code. The `$_scrollable` is false at the point of the calendar initialization. There was some Svelte store mechanism going on at that point and maybe the value wasn't set to `$_scrollable` fast enough.

It probably has something to do with how I'm initializing the Calendar, it's not very straight forward either - I'm using a certain JS framework.

Also not sure how to workaround it at this point.

**Comment by vkurko** [comment]
You may try creating a demo on [StackBlitz](https://stackblitz.com/).

**Comment by ile** [comment]
The more specific reason is that `afterUpdate()` isn't run after the component initialization.

I still don't have the demo, because the JS framework I'm using isn't actually public (it's forked from a public one though) - whe I get more time I could create the demo based on this original framework (https://derbyjs.com/).

**Comment by ile** [comment]
One other thing, I just use this same thread for now:

If you added this: `"main": "./index.js",` to the package.json in different packages (core, time-grid, interaction), then I could use the packages from a CommonJS project with a normal require() - no need for dynamic import.

It didn't seem to help the original issue though.

**Comment by ile** [comment]
I found the reason. There was some older Svelte code in the project with conflicted. Closing...
