### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'context')

### ISSUE THREAD

**Issue by FedeAlbe** [vkurko/calendar#219]
Hi sorry first time opening an issue. 

I was trying to use your component in a react app , but i don't why i can't make it work.

this is what i made up so far

   

<img width="669" alt="Screenshot 2024-01-16 alle 01 17 08" src="https://github.com/vkurko/calendar/assets/100215041/a55f5b46-dcbc-4e4e-b984-d42fb822b89e">
<img width="336" alt="Screenshot 2024-01-16 alle 01 16 58" src="https://github.com/vkurko/calendar/assets/100215041/370a384d-5ec8-42ab-8e32-10a68852459d">
<img width="711" alt="Screenshot 2024-01-16 alle 01 16 42" src="https://github.com/vkurko/calendar/assets/100215041/58053ef7-7561-4bd3-807c-7f0c29ba051a">

but i receive this error in the console
<img width="1494" alt="Screenshot 2024-01-16 alle 01 18 07" src="https://github.com/vkurko/calendar/assets/100215041/dbbf1e1b-520e-4566-9182-ad7929ec489b">

**Comment by vkurko** [comment]
Unfortunately, I don't have an example of using Event Calendar in React. For any such framework, the calendar should be initialized in a hook that is called after your component is mounted in the DOM. From your screenshots, it's not quite clear at what point the initialization occurs.

**Comment by vkurko** [comment]
@FedeAlbe any update?

**Comment by vkurko** [comment]
I hope I can close this issue.
