### ISSUE TITLE
Ability to disable editable on a per event basis

### ISSUE THREAD

**Issue by conoroshea1996** [vkurko/calendar#22]
Hey awesome library. 
We are currently using your library for our application works great.
One option that would be really helpful is to be able to disable or enable editing an event on a per event basis.

- Our use case is that we want to be able to only enable drag on one particular event.
![Capture](https://user-images.githubusercontent.com/47694309/131708842-10303cbc-0acb-4ff2-9818-01bd9d2e806b.PNG)

Is it possible to add an extra property to the event object that we can override editable on a per event basis

Something like this spotted on the fullcalendar docs

![image](https://user-images.githubusercontent.com/47694309/131709213-9ea5e598-ae6f-480e-97df-73197b021cb3.png)

Thanks

**Comment by vkurko** [comment]
Hi @conoroshea1996 

Thank you for the star!

The requested feature is available in v0.5.0 of the Event Calendar. Please note that there are 2 options that enable/disable the drag-and-drop feature - `editable` and `eventStartEditable`, so make sure you override both or the correct one with [editable and startEditable](https://github.com/vkurko/calendar#parsing-event-from-a-plain-object) properties of the Event object.

**Comment by conoroshea1996** [comment]
@vkurko That's brilliant
 thank you for your hard work. 
Great library to work with thanks again
