### ISSUE TITLE
Now Indicator

### ISSUE THREAD

**Issue by MaCleodWalker** [vkurko/calendar#221]
Is there a way to change the z index of the now indicator? it keeps being displayed over my modal even if the z-index of the modal is 99999.
![image](https://github.com/vkurko/calendar/assets/26272175/452eeca5-2f6b-40a8-9224-531fe3ee77b1)

**Comment by vkurko** [comment]
Of course, you can simply override the CSS rule for the `.ec-now-indicator` class. But be careful, most likely your modal is in a different [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context), so 99999 did not work, although the z-index of the indicator is 1005.

**Comment by vkurko** [comment]
I hope I can close this issue.

**Comment by MaCleodWalker** [comment]
Thank you, the issue was in fact the stacking context.

**Comment by vkurko** [comment]
Thanks for your sponsorship. It will be mentioned in the next release notes.
