### ISSUE TITLE
Undo editing before the current time

### ISSUE THREAD

**Issue by parismst** [vkurko/calendar#222]
Hello,

Is it possible that there is no editing capability before the current time?

![image](https://github.com/vkurko/calendar/assets/40799825/6299aea0-1b97-4709-bda1-03d66bf43172)

Thanks

**Comment by vkurko** [comment]
Hello,

There is no setting to automatically disable `dateClick` or dragging or resizing in that zone. You need to implement the checks yourself in the appropriate callbacks.

**Comment by vkurko** [comment]
I hope I can close this issue.
