### ISSUE TITLE
Unable to pass "headers" in EventSource POST

### ISSUE THREAD

**Issue by oldmanwerther** [vkurko/calendar#228]
When configuring to POST into my endpoint, it seems as if I can't add headers as a nested object in extraParams. The rendered payload shows as [object Object].

my js:
```
...
        eventSources: [
            {
                url: "https://localhost:44336/GetProducts",
                method: "POST",
                extraParams: {
                    mode: "cors",
                    referrerPolicy: "no-referrer",
                    headers: {
                        "Content-Type": "application/json",
                        "Accept": 'application/json'
                    },
                    body: bodyRequest
                }
            }
        ],...
```

**Comment by vkurko** [comment]
The `extraParams` option is intended only for additional parameters, not headers. Unfortunately there is no option for headers, but you can implement your own HTTP request via [eventSource as a function](https://github.com/vkurko/calendar?tab=readme-ov-file#2-execute-custom-function).

**Comment by vkurko** [comment]
Great!
