### ISSUE TITLE
イベントカレンダーの表示について

### ISSUE THREAD

**Issue by ryuhei-github** [vkurko/calendar#229]
@vkurko さん
イベントカレンダーについて質問があります。
縦表示になっているのを横表示に変更したいです。
もし可能でしたら手順を教えて下さい。

**Comment by vkurko** [comment]
Unfortunately, the calendar does not have a horizontal view. There is a [request for horizontal display of resources](https://github.com/vkurko/calendar/issues/30), but this is still not implemented.
