### ISSUE TITLE
Method like "gotoDate()"

### ISSUE THREAD

**Issue by alexandre-zamboli** [vkurko/calendar#231]
How can I navigate to a date?  and taking advantage of how can I make the days that are shown in the resource option start on a certain date?

**Comment by vkurko** [comment]
> How can I navigate to a date?

Just update the [date](https://github.com/vkurko/calendar?tab=readme-ov-file#date) option with `calendar.setOption('date', newDate)`

> how can I make the days that are shown in the resource option start on a certain date?

Maybe [firstDay](https://github.com/vkurko/calendar?tab=readme-ov-file#firstday) option?

**Comment by vkurko** [comment]
I hope I can close this issue.
