### ISSUE TITLE
nowIndicator line

### ISSUE THREAD

**Issue by mohamadjomah** [vkurko/calendar#233]
Hi, 

I want the red  nowIndicator line to be long to indicate every day of the week
Is this possible?

![image](https://github.com/vkurko/calendar/assets/83618430/630f8fda-fd67-4972-b24e-72812b19c430)

somthing like that:
![image](https://github.com/vkurko/calendar/assets/83618430/5e2af19b-0436-4ce8-b9cd-4d0bee0c04e8)

**Comment by vkurko** [comment]
No, unfortunately, there is no such option out of the box. I also don't see any way to easily do this using CSS.
