### ISSUE TITLE
Svelte 5 support

### ISSUE THREAD

**Issue by geoextra** [vkurko/calendar#235]
When using the `Calendar` component in a Svelte 5 project it relies on `get_current_component()` from `svelte/internal` which has been removed.
https://github.com/vkurko/calendar/blob/d337436bfebf7ddac21b1d787d5300f44744ef4d/packages/core/src/Calendar.svelte#L4

A possible solution is presented [here](https://github.com/sveltejs/svelte/issues/3091) with an [example](https://github.com/sveltejs/svelte/issues/9189#issuecomment-1794764745).

Tested with Svelte `5.0.0-next.50`.

**Comment by vkurko** [comment]
Thanks for the tip. Svelte 5 support will definitely come in the future.

**Comment by bayaderpack** [comment]
This is not only place with svelte/internal there is like 100 more places unfortunately

**Comment by dummdidumm** [comment]
Svelte maintainer here. I'm interested in why you had to reach into `svelte/internal`. When you start the migration towards Svelte 5, I'm curious to hear if there's anything that Svelte 5 lacks that you need to not reach into internals again.

**Comment by vkurko** [comment]
> Svelte maintainer here. I'm interested in why you had to reach into `svelte/internal`. When you start the migration towards Svelte 5, I'm curious to hear if there's anything that Svelte 5 lacks that you need to not reach into internals again.

Author of Event Calendar here :smiley:. @dummdidumm Thanks for the intervention. I would like to inform you that at the moment the migration to Svelte 5 has not yet been carried out.

The reason for using `svelte/internal` is that there are really useful functions there that will already be present in the final code, so it makes sense to reuse them in my library rather than write my own code. And for example `get_current_component()` it is impossible to write my own analogue.

**Comment by bayaderpack** [comment]
I'm just beginner but what about this $host rune maybe it can be used somehow?

**Comment by HoekWax** [comment]
Hello @vkurko, do you have a date in mind for svelte 5 support or not yet ? Thanks

**Comment by vkurko** [comment]
Not yet, unfortunately. Any support, including [sponsorship](https://github.com/sponsors/vkurko), is welcome.

**Comment by vkurko** [comment]
Not yet, unfortunately. Any help in this matter, including [sponsorship](https://github.com/sponsors/vkurko), is welcome.

**Comment by itsmikesharescode** [comment]
I love this project hoping for svelte 5 support!

**Comment by rgon** [comment]
I have made an attempt at fixing this. I have vendorized the svelte/internal methods that are used and shouldn't be used now.

However, in this attempt, I have dropped support for the `destroy()` method. It's the only method that requires `get_current_component` from the internal API, which is quite conflictive. Also, if I may ask so, what's the point of having a destroy() method? Especially now that it bypasses the internal workings of Svelte, and this is the only library I've seen do this. You could achieve the following with the idiomatic:

```svelte
{#if notDestroyed}
<Calendar />
{/if}
```

This would call all the built in constructors/destructors and not cause the potential void/null object situation destroying the element manually would.

AFAIK, we cannot implement the solution mentioned by @geoextra would not allow to call the destruct method from within the component, but rather from an external class.

**Comment by vkurko** [comment]
> I have vendorized the svelte/internal methods that are used and shouldn't be used now.

Thank you for your contribution! I will review and accept your PR later.

**Comment by vkurko** [comment]
> what's the point of having a destroy() method?

This method is required when using the library outside of Svelte. The simplest example is using the Event Calendar inside a Vue.js component, where when the Vue component is destroyed, the calendar should be destroyed too.



> You could achieve the following with the idiomatic:
> ```svelte
> {#if notDestroyed}
> <Calendar />
> {/if}
> ```

Well, this is not exactly the equivalent of the current solution. It involves another wrapper component that will hide from the outside world all the methods of the Calendar component that it exposes.

I'm still looking for a solution.

**Comment by dummdidumm** [comment]
If this should be usable standalone, I suggest to create a `index.js` from which you expose a custom method that suits your use case, using `mount` and `unmount` from `svelte`:

```js
import { mount, unmount } from 'svelte';
import Calendar from './Calendar.svelte';

export function create(target, props) {
  const instance = mount(Calendar, { target, props });
  return {
     instance,
     destroy: () => unmount(instance)
  }
}
```

**Comment by vkurko** [comment]
v3.6.0 is now available with fixes from @rgon. The `destroy()` method remains available only in pure JS and pre-built versions of the library.

**Comment by vkurko** [comment]
> v3.6.0 is now available with fixes from @rgon. The `destroy()` method remains available only in pure JS and pre-built versions of the library.

Sorry, in v3.6.0 the destroy is only available in pre-built version. The ES version will be fixed in the future release.

**Comment by vkurko** [comment]
> The ES version will be fixed in the future release.

Done in v3.6.1.
