### ISSUE TITLE
Is there a changeview API like fullcalendar?

### ISSUE THREAD

**Issue by izu12ki** [vkurko/calendar#236]
Fullcalendar has changeview API.
https://fullcalendar.io/docs/Calendar-changeView

Does this library also have the same API?
If not, are there any ways to change view on dateClick?

Thank you for this great library.

**Comment by vkurko** [comment]
Just update the [view](https://github.com/vkurko/calendar?tab=readme-ov-file#view) option with `calendar.setOption('view', newViewName)`.

**Comment by izu12ki** [comment]
Thanks for the quick reply.
That worked!
