### ISSUE TITLE
Is there a way to set the z index per event?

### ISSUE THREAD

**Issue by MaCleodWalker** [vkurko/calendar#239]
Im using eventClassNames and TailwindCSS to set some custom classes for events.  Im trying to use the tailwind classes 'z-10 hover:z-50 hover:min-w-min' to show all the event content when hovered but it seems like the resources are stacked left to right.
![image](https://github.com/vkurko/calendar/assets/26272175/24be0842-1011-42e0-99bc-34dbee041f98)

**Comment by vkurko** [comment]
On the demo I added a CSS rule `min-width: min-content;` for the blue event and it seemed to work.

![image](https://github.com/vkurko/calendar/assets/1073174/d86d9e63-b7de-4eb6-8059-d107f8eab825)

Can you provide an online demo of the problem so I can check?

**Comment by MaCleodWalker** [comment]
I'm not sure what was causing the issue but when i started my dev server today the issue was no longer present. 

Thank you for all your work.
