### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by oyejorge** [vkurko/calendar#241]
Hi, I wanted to play around with the code but I can't seem to get the local development server working.

`npm run build` seems to work

but

`npm run start` throws 
> Error: ENOENT: no such file or directory, scandir '/[folder]/vkurko-calendar/public'

`npm run dev` starts a server on localhost (for example  http://localhost:37825) but any request to the server results in a `404 Not Found`

Any advice on how to run things locally?

**Comment by vkurko** [comment]
Hello,

Please use [this](https://github.com/vkurko/calendar/discussions/59#discussioncomment-3623690) as a reference.
