### ISSUE TITLE
Delete/Edit Icon on Event in React

### ISSUE THREAD

**Issue by U4I-pradeep-gill** [vkurko/calendar#25]
Is it possible to add a Delete/Edit event icon, while using below code:- 
```
props: {
        plugins: [TimeGrid],
        options: {
          view: "timeGridWeek",
          height: "700px",
          events: events,
          dateClick: (dateClickInfo) => {},
          eventClick: (eventClickInfo) => {}
        }
     }
```

**Comment by vkurko** [comment]
Hey @U4I-pradeep-gill.

The  `event-calendar.min.js` script is a pre-built bundle ready for use in [browsers](https://github.com/vkurko/calendar#browser-support). It includes all the plugins available in the Event Calendar, i.e. `@event-calendar/core`,  `@event-calendar/day-grid`,  `event-calendar/list`,  `@event-calendar/time-grid`,  `@event-calendar/resource-time-grid` and `@event-calendar/interaction`.

So it basically depends on your environment. If your application will run in an environment that supports ES6, then you can simply import the required Event Calendar package into your project. If you need ES5, then most likely you'll additionally use a compiler, like `BabelJS`.

The `event-calendar.min.js` is the result of compiling the source code with BabelJS for browsers including IE11. If you do not need IE11, then there is a nother build `event-calendar-modern.min.js`.


1. For the drag&drop you also need to include the `@event-calendar/interaction` plugin.
2. This may happen when you setup the Event Calendar to fetch events from an [event source](https://github.com/vkurko/calendar#eventsources). You add an event using the `addEvent` method, change the current range, and the Events Calendar fetches the data for the new range from the event source. Eventually the events received from the source are displayed. If this is not your case, then please create a [JS Bin](https://jsbin.com/) example that reproduces the problem.

**Comment by U4I-pradeep-gill** [comment]
Installed the updated version 0.7.1 and it works as expected :)
Thank you :)
