### ISSUE TITLE
Support to reset events.

### ISSUE THREAD

**Issue by phpcodebooster** [vkurko/calendar#253]
Right now when I load calendar initially I add all events. However when view changes from day to say week. I need to re fetch events based on week timeframe. This causes duplication in same events within a period earlier.

**Comment by vkurko** [comment]
Something is most likely wrong with the way you are loading data into the calendar. You don't need to force `refetchEvents()` to be called when navigating the calendar if you use [eventSources](https://github.com/vkurko/calendar#eventsources). Can you show your code to make it clearer?

**Comment by vkurko** [comment]
> Can you show your code to make it clearer?

@phpcodebooster any update on this?

**Comment by phpcodebooster** [comment]
@vkurko here is the sample code look like

`onMounted(async () => {
  eventCalendar = new Calendar({
    target: calendarRef.value,
    props: {
      plugins: [TimeGrid, DayGrid, ListGrid, Interaction],
      options: {
        view: 'timeGridWeek',
        headerToolbar: {
          center: 'title',
          start: 'prev,next today',
          end: 'listWeek,timeGridDay,timeGridWeek,dayGridMonth'
        },
        datesSet: function ({ view }: any) {
          fetchEvents({
            end_at: toMySQLDate(view.currentEnd),
            start_at: toMySQLDate(view.currentStart)
          })
        },
        eventClick: function ({ event }: any) {
          const meta = event.extendedProps
          const end = formatToIso8601(event.end)
          const start = formatToIso8601(event.start)

          eventStore.set({
            ...meta,
            end_at: end,
            start_at: start
          })
        },
        eventDrop: function ({ event }: any) {
          const meta = event.extendedProps
          const end = formatToIso8601(event.end)
          const start = formatToIso8601(event.start)

          eventStore.save(event.id, {
            end_at: end,
            start_at: start
          })
          eventStore.set({
            ...meta,
            end_at: end,
            start_at: start
          })
        }
      }
    }
  })
})`

**Comment by phpcodebooster** [comment]
@vkurko can you show me an example of how event source can be used effectively?

1. on initial load fetching remote events
2. creating new event and adding it manually to calendar works fine
3. when I change calendar view from say week to month and call eventCalendar.updateEvent(e)) creates duplicates

**Comment by vkurko** [comment]
Please see [this comment](https://github.com/vkurko/calendar/discussions/203#discussioncomment-7550815). If you still need further clarification, I will try to help.

**Comment by phpcodebooster** [comment]
@vkurko thanks for details I resolved this issue however now I am seeing different issue.

1) in my calendar toronto time GMT -4 hours. I am saving an event from 02:00 AM to 06:00 AM
2) I am saving this event in my database 
 "end": "2024-04-10T10:00:00+00:00",
 "start": "2024-04-10T06:00:00+00:00"
as UTC time because UTC is ahead 4 hours
3) when i supply this UTC date as events in my calendar my calendar shows me this event starts at 06:00 to 10:00 AM this is incorrect. I should see my original event time in my calendar which should be -4 hours behind UTC if given dates are in UTC 
 "end": "2024-04-10T10:00:00+00:00",
 "start": "2024-04-10T06:00:00+00:00"

it should show me 02:00 AM to 06:00 AM not 06:00 AM to 10 AM

**Comment by vkurko** [comment]
Unfortunately, time zones are not currently supported in Event Calendar. Therefore, you need to convert the time yourself, for example, on the server side when preparing a response to the calendar.
