### ISSUE TITLE
Is it possible to have a single line for 2 events starting/ending on half a day?

### ISSUE THREAD

**Issue by htodep** [vkurko/calendar#257]
Is it possible to have an event starting at the half of the day and ending at the half of the day, and also have the same event on 1 line?  See image(design) for example:

![image](https://github.com/vkurko/calendar/assets/59797138/d72f2c1e-77ed-4bfc-92c2-5bd0108e01d7)

**In context:**
We have a calendar overview where you can see which holiday home has been booked when and by whom.
When you look at the image you can see that Villa Bona Vista(first event in pink) has been booked from the 26th untill the 30, there is another booking for the same house (Villa Bona Vista) from the 30th untill the 4th(second row).

**This is what we have right now:**
![image](https://github.com/vkurko/calendar/assets/59797138/dd8efd26-caa8-4b23-abe3-7783f40c7058)
Here you can see that the two pink events are not aligning on the same row.

**Comment by vkurko** [comment]
I get the idea, but unfortunately this type of event layout is not supported. Perhaps the not yet implemented [resource horizontal view](https://github.com/vkurko/calendar/issues/30) will be able to display something similar to what you need. But for now I can’t give any time estimates on when it will be ready.

**Comment by htodep** [comment]
Oke, good to know. Thanks for the quick response!
