### ISSUE TITLE
Horizontal view

### ISSUE THREAD

**Issue by steveb85** [vkurko/calendar#258]
@vkurko thanks so much. have loved for a long time.

Would be willing to work with and pay or help pay or do whatever is needed to have an option for a horizontal view as well, I have sorted a nice horizontal scroll option inside the calendar but i'm talking about a complete axis switch with timeline on the x axis and dates and or resources on the y axis. would not be replacing this but as an additional view. 

thanks all,. Steve

**Comment by vkurko** [comment]
Hello @steveb85. Recently, the opportunity to become a [sponsor](https://github.com/sponsors/vkurko) of the Event Calendar has become available. This will really help me to allocate time for further development of the library.

Also, any initiative to independently develop new features and add them to the library through pull requests is also welcome.

**Comment by steveb85** [comment]
@vkurko is there a way to reach out to you directly, will sign up as a sponsor as well but would like to discuss some things as well on top of that ? thanks  steve

**Comment by vkurko** [comment]
Sure, [2vkurko@gmail.com](mailto:2vkurko@gmail.com).

I'm closing this ticket in favor of the [older](https://github.com/vkurko/calendar/issues/30) one.
