### ISSUE TITLE
Inside of a kit app

### ISSUE THREAD

**Issue by lmcardle** [vkurko/calendar#26]
Have you used this library inside of a svelte kit based application? I’m trying it out and not able to render it because of an error stating that *Calendar* is not SSR compatible.

**Comment by half2me** [comment]
Do you have any plans to support SvelteKit? I'd really like to use it in my SvelteKit app.

**Comment by vkurko** [comment]
Hi @half2me 

I think, yes. But give me a few days to answer the question more precisely.

**Comment by half2me** [comment]
@vkurko thanks for the reply. Sure thing. If you need some help with it I'm happy to assist.

**Comment by vkurko** [comment]
@lmcardle @half2me 

I finally took the time to look at SvelteKit. It seems that it was only needed to include the source files in the Event Calendar packages and fix a weird bug in dev mode of Vite or SvelteKit (I couldn't figure out exactly where the problem comes from).

Can you try Event Calendar v0.8.2 and tell me if it works for you?

**Comment by half2me** [comment]
@vkurko
Seems like sass is now a dependency, cause I get: `[vite] Internal server error: Preprocessor dependency "sass" not found. Did you install it?`

After installing sass as a dev dependency, it works as expected in the kit app.

**Comment by vkurko** [comment]
Yes, I noticed this problem after v0.8.2 was published. I also don't like that now the calendar doesn't work in normal Svelte app (not SvelteKit) for the same reason - you need to configure `sass`.

So far I haven't found a good solution.

**Comment by vkurko** [comment]
@half2me 

I decided to replace `scss` with compiled `css` before publishing the package. So now there should be no dependency on `sass`.

Please check v0.8.3.

**Comment by half2me** [comment]
@vkurko works well, thanks :)

**Comment by vkurko** [comment]
Great! Closing this ticket then.

**Comment by adzcai** [comment]
I'm running into a similar issue on version 2.6.1, thought I would reopen:
```
Error: <Calendar> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <Calendar>.
```
