### ISSUE TITLE
Incorrect behaviour with dayMaxEvents + height:100%

### ISSUE THREAD

**Issue by ilajosmanov** [vkurko/calendar#264]
Hey! Thanks for the library, I see you've done really hard work!
I've noticed that if I have a lot of events and height of my calendar is `100%`, only resizing helps to get them to groups.

There is link for reproduce
https://app.vidcast.io/share/b661f8d6-82c9-4d2c-9978-849fd7f8dcc4

**Comment by vkurko** [comment]
> There is link for reproduce
> https://app.vidcast.io/share/b661f8d6-82c9-4d2c-9978-849fd7f8dcc4

Sorry, can you provide a public link please? Currently it asks to sign in.

**Comment by ilajosmanov** [comment]
@vkurko sorry, I made it public

**Comment by vkurko** [comment]
Thank you. I'll fix it soon.

**Comment by vkurko** [comment]
@ilajosmanov The problem should be fixed in v2.7.1. Please check.

**Comment by ilajosmanov** [comment]
It works, thanks!
