### ISSUE TITLE
custom button about

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#265]
Hello Viladimir,
Thanks for everything this library.
I want a new feature, I don't know if there is one. I want to add a custom buttons.
textbox, input:radio, input:checkbox and add custom class this elements.
(i want to write custom html.)
is it possible?

I see this sample code in the documentation.
But for me this is not enough.

`customButtons: {
            myCustomButton: {
                text: 'custom!',
                click: function() {
                    alert('clicked the custom button!');
                }
            }
        },
        headerToolbar: {
            start: 'prev,next today title',
            center: 'input:text',
            end: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek,listDay resourceTimeGridDay'
        },`

**Comment by vkurko** [comment]
Hello Emrah,

I don't think the calendar should separately support checkboxes, radio buttons, etc. Perhaps custom html, but no more.

In general, it seems to me that in your case the right decision would be to refuse to use the built-in toolbar. Instead, you could make your toolbar completely separate from the calendar and implement your own buttons for switching views and navigation.
