### ISSUE TITLE
Cant scroll horizontal on resource view 

### ISSUE THREAD

**Issue by kstan79** [vkurko/calendar#268]
as below example i define multiple resources, it shrink down the column so tiny and cause the event cant render well.
![sample1](https://github.com/vkurko/calendar/assets/1889979/951e0e53-785f-46ec-8dea-2c2ef9123afa)

I'm tried to change css to set min-width.
```css
.ec-resource{
    @apply !min-w-32
}
```
so far column width expand but cause issue like it cant render calendar well. I tried multiple way and no luck, result either:
1. some resource draw outside calendar boundary (teacher8 & unknown outside calendar)
2. or i freeze body width 100vw and no overflow-x scrollable will cause below
![sample2](https://github.com/vkurko/calendar/assets/1889979/e9c4b4ef-ed92-4ef5-b801-c17505b5446e)
![sample3](https://github.com/vkurko/calendar/assets/1889979/a0c92144-5ad6-4f70-a879-d3726c2b7130)

is there anyway can render calendar nicely when render near 40 resources?

**Comment by kstan79** [comment]
i manage to solve by manually set 'ec' width at runtime:
```ts
const colwidth = 8 //rem
const calResources = getResources()
const totalwidth = calResources.length * colwidth + 3 //+3rem require for times column
      if(document.getElementById('ec')!== undefined){
        document.getElementById('ec').style.width = totalwidth+'rem'
      }
```

however, I not think it is a good and permanent solution (maybe different browser will have different issue), so far any more "official" way?

**Comment by vkurko** [comment]
Please take a look at this [comment](https://github.com/vkurko/calendar/discussions/242#discussioncomment-8701903). The official solution to this issue will be [Resource Timeline](https://github.com/vkurko/calendar/issues/30) view, which is currently in development.
