### ISSUE TITLE
Change dayGrid

### ISSUE THREAD

**Issue by mustafaabduljalil** [vkurko/calendar#27]
can i replace dayGrid (days on the top of calendar) with users name ?

**Comment by vkurko** [comment]
Hi @mustafaabduljalil 

You can use a function for the [dayHeaderFormat](https://github.com/vkurko/calendar#dayheaderformat) option and return any text you like. Will this work for you?

**Comment by vkurko** [comment]
Please open a new issue if you have further questions.
