### ISSUE TITLE
Custom attibutes for custom buttons

### ISSUE THREAD

**Issue by jnegron357** [vkurko/calendar#277]
The new Custom Buttons feature is great but it needs to provide a mechanism for providing values to certain native attributes or events and provide custom attributes as needed (ie: data-[attribute/property]). I propose a new property for the custom button that can take a JSON string that will provide the definitions for attributes:
`{ 
      id: 'myId',
      class: 'my-class-names',
      onMouseOver: 'myHoverFunctionName',
      dataIndex: '0',
      dataId: '12345678',
      dataCategory: 'MyValue'
  }`

**Comment by vkurko** [comment]
Thanks for your suggestion. Perhaps I'll just implement the ability to use custom html instead of a button.

**Comment by vkurko** [comment]
@jnegron357  In Event Calendar v3.2.0, it became possible to pass `html` as the title for a custom button. Yes, this is not what you asked for, but it’s better than what it was :smile:

**Comment by jnegron357** [comment]
This is great, thank you so much!
