### ISSUE TITLE
Expose API for next and previous actions

### ISSUE THREAD

**Issue by haovoanh28** [vkurko/calendar#279]
Hi,

In my web app, the calendar has four different view types. Due to certain requirements, I need to implement a custom toolbar instead of using the built-in one. 
When working on the next and previous actions, I realized that my solution is rather cumbersome, as I have to handle each action in 4 different ways, resulting in a total of 8 different approaches.

Is is possible to expose an API for next and previous actions, similar to FullCalendar, so that I can simply call it and have everything work as expected ?

Thank for your time.

**Comment by vkurko** [comment]
Ok, I'll implement this.

**Comment by haovoanh28** [comment]
Thank you

**Comment by vkurko** [comment]
The [next](https://github.com/vkurko/calendar?tab=readme-ov-file#next) and [prev](https://github.com/vkurko/calendar?tab=readme-ov-file#next) methods should be available in v3.1.0. Please check.

**Comment by haovoanh28** [comment]
I checked.
It works well, thanks.
