### ISSUE TITLE
Add week number in title

### ISSUE THREAD

**Issue by Retrovers** [vkurko/calendar#285]
Hi, 
In the current version, is there a way to add the number of the week to the title? 
If not, is this addition planned?

Thank you for your incredible work

**Comment by vkurko** [comment]
The [titleFormat](https://github.com/vkurko/calendar?tab=readme-ov-file#titleformat) option takes as a parameter an arbitrary function in which you can format the date yourself, for example, using a third-party library [[1]](https://date-fns.org/v3.6.0/docs/format) that can format the week number in the year.

**Comment by Retrovers** [comment]
Ok thanks you
