### ISSUE TITLE
Now indicator

### ISSUE THREAD

**Issue by paubikas** [vkurko/calendar#29]
Do you have plan to add now indicator like in fullcalendar?

**Comment by vkurko** [comment]
Hi @paubikas 

Thanks for the suggestion. I'll take a look at the FC implementation and most probably will do it in the Event Calendar

**Comment by vkurko** [comment]
Hi @paubikas 

The [nowIndicator](https://github.com/vkurko/calendar#nowindicator) option in available in Event Calendar v0.8.0. Please check.

**Comment by DNWEIJ** [comment]
Hi there, 

It works! :-)
But.... :-( 
It doesn't take into account the following....
            slotMinTime: '08:00:00',
            slotMaxTime: '17:00:00',

So now the indicator is standing outside of the time box (at the moment it's 20:55. 
The indicator is now placed outside the actual allowed time frame.

Would it be possibe to not placed it when it is outside the min-max period?

**Comment by vkurko** [comment]
Hi @DNWEIJ 

You're right! I released v0.8.1 with some fixes for this issue. Please check.

**Comment by DNWEIJ** [comment]
ok, nice that works.! :-)

**Comment by vkurko** [comment]
Great!
