### ISSUE TITLE
starting date

### ISSUE THREAD

**Issue by NikitaSchreyder** [vkurko/calendar#290]
hi, how can I set the date from which to start showing? 
for example, I need to show data from 06/04 to 06/13
i use resourceTimelineMonth

**Comment by vkurko** [comment]
The currently displayed date is set by the [date](https://github.com/vkurko/calendar#date) option. If you want to limit the displayed dates so that you cannot navigate the calendar to other dates, then there is no such option yet, check [here](https://github.com/vkurko/calendar/issues/141).
