### ISSUE TITLE
Style Event Without Classes

### ISSUE THREAD

**Issue by AdrianGzzEsc** [vkurko/calendar#298]
I would like to show some kind of progress bar on the event and use something like "background-image: linear-gradient(90deg, black 50%, blue 50%);"
the percentage will be different on each event so I would like to style it, saddly the background-color property doesnt work with linear-gradient so Im trying to find a way to attach it to the event. 

I tried editing the DOM element after the view is loaded but If I drag an event it refreshes or something cause the added css dissapears

My 2 ideas are, finding a way to add style to specific event and its saved or somehow make the .backgroundColor property edits "background-image"  instead of "background-color"

**Comment by vkurko** [comment]
Unfortunately, there is currently no way to easily set styles for an event. Perhaps you can achieve what you need by using [eventContent](https://github.com/vkurko/calendar?tab=readme-ov-file#eventcontent) and rendering your specific content with the desired background?

**Comment by vkurko** [comment]
Great!
