### ISSUE TITLE
I used the script from CDN however drag and resize isnt working 

### ISSUE THREAD

**Issue by xsudiptaster** [vkurko/calendar#299]
I tried to integrate the Gantt on Salesforce. the Gantt displays well however resize or drag doesn't work. I used the code as stated in the example nothing extra.

**Comment by vkurko** [comment]
The [demo](https://vkurko.github.io/calendar/) also uses the CDN version of the library. As you can see drag and drop works there. Most likely there is something wrong in your code. Look for errors in the console or provide a public link so I can check.

**Comment by vkurko** [comment]
I hope I can close this issue.
