### ISSUE TITLE
Resource view - horizontal

### ISSUE THREAD

**Issue by Tomasz-InterStudio** [vkurko/calendar#30]
Hello, it looks good. Nice work 👍 

I have question, its posible to configure `resource view` to look something like this:
![getIS](https://user-images.githubusercontent.com/76209189/150978967-5e4418fc-62a2-4c01-b7bc-b1f43b447df9.png)

If its possible, how can achive that look ?

**Comment by vkurko** [comment]
Hi @Tomasz-InterStudio 

Thank you for the star! :smile: 

Unfortunately, this view is not available in Event Calendar. I'll leave this ticket open for others to vote on its implementation.

**Comment by gioramies** [comment]
+1

**Comment by emrahnalci** [comment]
+1

**Comment by mrvnklm** [comment]
+1

**Comment by gocarlos** [comment]
seems to be the most upvoted issue here, let us know if we can help by contributing or sponsoring

**Comment by vkurko** [comment]
> seems to be the most upvoted issue here, let us know if we can help by contributing or sponsoring

Sponsorship is very welcome, but I used to have a sponsorship link and the total amount for last year was $0 :smile:. I recently removed this link.

Contribution is also welcome and there is already a positive experience. For example, all-day events were [implemented](https://github.com/vkurko/calendar/pull/42) by a third party developer. If someone can take on the implementation of horizontal resource view, then I can then look at the code and correct it if necessary, the main thing is to start.

**Comment by steveb85** [comment]
+1

**Comment by stescacom** [comment]
https://github.com/vkurko/calendar/discussions/242#discussioncomment-8701903

Horizontal scroll..

**Comment by steveb85** [comment]
I figured a way to get horizontal scroll working @stescacom  after a lot of working around. lmk if you're interested.

**Comment by vkurko** [comment]
The first version of the horizontal resource view, called `ResourceTimelineWeek`/`ResourceTimelineDay` view, is now available in v3.0.0.

**Comment by vkurko** [comment]
For any enhancements, please open a new issue.

**Comment by jainkuniya** [comment]
hi, any plans to add `nowIndicator` in `resourceTimelineWeek/resourceTimelineDay` ?
