### ISSUE TITLE
addEvent method does not return Event object

### ISSUE THREAD

**Issue by rrimsa** [vkurko/calendar#301]
Hello,

The title sums it up.

Check out the eventObject variable after creating an event by clicking on a date: [fiddle](https://jsfiddle.net/xshueka4/)

I also tested with fullcalendar, and fullcalendars method actually returns the Event object.

Best regards.

**Comment by rrimsa** [comment]
Made some minor changes and created a pull request.

**Comment by vkurko** [comment]
Thank you very much for your contribution. I will review and accept your pull request soon.

**Comment by vkurko** [comment]
This is fixed in v3.4.0.
