### ISSUE TITLE
Feature Request - Resource Timeline Hierarchical

### ISSUE THREAD

**Issue by martinfruehmorgen** [vkurko/calendar#302]
Hello,
And thank you so much for this library!

In there a chance to implement hierarchical resources in the resource timeline view?
See the demo here:
https://fullcalendar.io/demos
and there "Resource timeline".

Thank you!
Martin

**Comment by lukacavic** [comment]
+1 for this

**Comment by vkurko** [comment]
I think this will be implemented in the future. I ask all those interested to check in and like this post.

**Comment by inu-web** [comment]
+1

**Comment by vkurko** [comment]
Nested resources is now available in v3.7.0.
