### ISSUE TITLE
How to get HTML element of event from the getEventById function?

### ISSUE THREAD

**Issue by Retrovers** [vkurko/calendar#307]
Hello devs, 
Is there a way to get the HTML element of event from the getEventById function?

Thanks in advance.

**Comment by vkurko** [comment]
What exactly do you need the html element for? Please explain. Maybe one of the callbacks, for example, [eventDidMount](https://github.com/vkurko/calendar?tab=readme-ov-file#eventdidmount) or [eventContent](https://github.com/vkurko/calendar?tab=readme-ov-file#eventcontent), will suit your needs.

**Comment by Retrovers** [comment]
I'd like to get the positioning details of an event's div (boundingClientRect) for a contextual menu.

**Comment by vkurko** [comment]
There are different callbacks where this can be done. For example, if the menu is initialized when an event is clicked, then the [eventClick](https://github.com/vkurko/calendar?tab=readme-ov-file#eventclick) callback contains information about the html element. If the initialization must be done in advance, you can use [eventDidMount](https://github.com/vkurko/calendar?tab=readme-ov-file#eventcontent).

**Comment by vkurko** [comment]
I hope I can close this issue.
