### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by DrogazDev** [vkurko/calendar#311]
hey, when i add a locale to the options ('nl') the days abbreviation and dates and such are correctly translated, but month,week,day buttons & the all-day doenst translate. Is there a way for me to translate this manually?

![image](https://github.com/user-attachments/assets/3884625f-a9ec-4b4f-95dc-8d4ecbcee63f)

**Comment by vkurko** [comment]
Yes, to change those texts, use the [buttonText](https://github.com/vkurko/calendar?tab=readme-ov-file#buttontext) option:

```js
buttonText: function (text) {
    text.today = 'Vandaag';
    text.month = 'Maand';
    ...
    return text;
}
```

**Comment by DrogazDev** [comment]
Thx for the help, overlooked it :)
