### ISSUE TITLE
Date on IPAD

### ISSUE THREAD

**Issue by gpizzetta** [vkurko/calendar#312]
Hi

I just discover that some events does not display on IOS (iPadOS 17.6.1) and calendar version 3.1.0 
I first thought it was an issue from the calendar but I finally found the issue comes from me. 

My hours where not correctly formatted the string was 12:0 instead of 12:00 

New Date() function on iPad did not like that.

I still add this issue since it can help others and it was the occasion to thank you for this great job

Gilles

**Comment by vkurko** [comment]
Thanks for the information.
