### ISSUE TITLE
Bottom dot on reize a bar

### ISSUE THREAD

**Issue by kawasaki656** [vkurko/calendar#316]
Is it possible to add dots like it's implemented in fullCalendar on reizing a bar ?
![image](https://github.com/user-attachments/assets/64babc06-51b4-4ed9-bd35-539bea48d65d)

**Comment by vkurko** [comment]
You have full control over the CSS. I think it wouldn't be too hard to make such a dot if you spend a little time on it.

I don't plan to do it in the library itself at the moment.
