### ISSUE TITLE
headerToolbar content 

### ISSUE THREAD

**Issue by noneym** [vkurko/calendar#32]
Hello,
First of all, I have to say that you wrote a great script. 
i have a little problem ;
Is there a method where I can edit the headerToolbar design? like a eventContent  method.

**Comment by vkurko** [comment]
Hi @noneym 

There is [headerToolbar](https://github.com/vkurko/calendar#headertoolbar) option :smile: What specifically are you missing? Can you refer to the appropriate FullCalendar option?

**Comment by noneym** [comment]
Actually, I needed something that I could change the html but I solved it with js thank you again
