### ISSUE TITLE
strange behavior with dateset 

### ISSUE THREAD

**Issue by colinhobbs** [vkurko/calendar#324]
Maybe i'm doing something wrong here.  I created a small calendar and was testing the prev and next functions. 
`const ec = new EventCalendar(document.getElementById('ec'), {`
`            view: 'dayGridMonth',`
`           headerToolbar: {`
`                start: 'prev,next today',`
`                center: 'title',`
`                end: 'dayGridMonth',`
`            },          `
`            datesSet: function(info) {                                  `
`                    console.log("gimme fetchInfo.startstr " +  info.startStr);`
`            },`
`        });`
when initially loading the calendar  I get the correct month ( 09 ) on the console. 
 **console:**  gimme fetchInfo.startstr 2024-09-01T00:00:00
 click the previous month button once i get
**Console:** gimme fetchInfo.startstr 2024-07-28T00:00:00     ( shouldn't that be 08? )
calendar header shows August 2024 
click next month 
 **console:**  gimme fetchInfo.startstr 2024-09-01T00:00:00
calendar header shows September 2024 
click next month 
 **console:**  gimme fetchInfo.startstr 2024-09-01T00:00:00
calendar header shows October 2024 
click next month 
 **console:**  gimme fetchInfo.startstr 2024-10-01T00:00:00
calendar header shows November 2024 

using <script src="https://cdn.jsdelivr.net/npm/@event-calendar/build@3.4.0/event-calendar.min.js"></script>

**Comment by vkurko** [comment]
The `start` value in `datesSet` means the beginning of the displayed range. In monthly mode, days from adjacent months are often displayed as well. Note the very first day you see in the first row of the calendar for August 2024. Most likely, you will have July 28 there.

**Comment by colinhobbs** [comment]
ok..  I do see that now .. thanks..
