### ISSUE TITLE
Theming specific days or dates? (e.g. for days off, holidays)

### ISSUE THREAD

**Issue by DocBouCou** [vkurko/calendar#328]
Hi,

I would like to know if it is possible to theme some particular dates? 

For instance, today is "highlighted" in pale yellow. I would like to color in pale grey the days off (sundays, national holidays, or any days my users are not working, for instance). 

Is it currently possible? If yes, how would I do that? If no, do you think you might implement this feature?

Regards, and thank you for the great work

**Comment by vkurko** [comment]
There is [highlightedDates](https://github.com/vkurko/calendar?tab=readme-ov-file#highlighteddates) option. Also you can use `background` events to grey out particular days or times.

**Comment by DocBouCou** [comment]
Thank you very much :-)
