### ISSUE TITLE
Can I set non-clickable hours for resources?

### ISSUE THREAD

**Issue by noneym** [vkurko/calendar#33]
Hello Vladimir
Can I set non-clickable hours for resources? The unclickable time of each resource can be different.

![image](https://user-images.githubusercontent.com/190996/159188361-f455101c-8011-4bfc-8065-91d330c779b1.png)

**Comment by vkurko** [comment]
Hi @noneym,

Please see this [comment](https://github.com/vkurko/calendar/issues/31#issuecomment-1031352102). Perhaps this is what you need. Let me know.

**Comment by noneym** [comment]
yes like that. but it will only be for some hours of some resources. I couldn't figure out how to do this.

**Comment by vkurko** [comment]
Both the [eventContent](https://github.com/vkurko/calendar#eventcontent) and the [dateClick](https://github.com/vkurko/calendar#dateclick) options contain information about which resource the click or the `pointer` event belongs to. So you can use this information to make different behaviors for different resources.

**Comment by noneym** [comment]
hello Vkurko, 

The example you mentioned does not work in the eventSources method. 
actually, it would be great if there was a method where we can change the background color of the calander for each resource according to the time interval.

**Comment by vkurko** [comment]
Can you explain what exactly doesn't work? The [eventContent](https://github.com/vkurko/calendar#eventcontent) and the [dateClick](https://github.com/vkurko/calendar#dateclick) do not rely on `eventSources`.

It would be helpful if you provided an example in [JS BIn](https://jsbin.com) (or any other similar tool).

**Comment by vkurko** [comment]
If you have more questions, feel free to reopen the ticket.
