### ISSUE TITLE
Cannot read properties of undefined (reading '$$')

### ISSUE THREAD

**Issue by DGibbsCrafted** [vkurko/calendar#331]
Hi, I'm trying to setup a quick demo project using this plugin in Vue 3 and am following the ES6 module approach.

When doing this I'm finding that it throws an error on when setting the `root` config property:

![image](https://github.com/user-attachments/assets/bf894749-77d6-4362-8595-782e33f65f38)

Here's a codesandbox with the issue:
https://codesandbox.io/p/sandbox/qkqp4z

I've followed the 'Usage' / getting started guide in the read me but this approach doesn't seem to work. How can I get a basic implementation running in Vue?

**Comment by satoryu** [comment]
I'm running into the same problem.

**Comment by vkurko** [comment]
> Here's a codesandbox with the issue:
> https://codesandbox.io/p/sandbox/q2ydvz

Can you make it publicly available?

**Comment by DGibbsCrafted** [comment]
@vkurko Apologies, I shared the wrong link.

Here you go: https://codesandbox.io/p/sandbox/qkqp4z

**Comment by vkurko** [comment]
It's something with the `codesandbox`. I copied your code to Stack Blitz and the problem does not reproduce there https://stackblitz.com/edit/vitejs-vite-zweske?file=src%2Fcomponents%2FHelloWorld.vue

**Comment by DGibbsCrafted** [comment]
@vkurko - You're correct, I can confirm it works outside of codesandbox. I think we can close this as a non-issue. Thank you for your time investigating!
