### ISSUE TITLE
Unable to Display Events Beyond Midnight in resourceTimelineDay View

### ISSUE THREAD

**Issue by volpeo** [vkurko/calendar#333]
Hello! First of all, thank you for developing such a fantastic tool. 

I’ve encountered an issue with displaying events beyond midnight on the resourceTimelineDay view that I hope you can help me resolve.

I use a `resourceTimelineDay` view with the following options:
```
type: 'resourceTimeline',
duration: { days: 1 },
slotMinTime: '06:00',
slotMaxTime: '28:00',
```

I then added an event that starts during the day and finishes after midnight.

The event starts at the correct time but is cut off at midnight. Even when attempting to move the event, it remains truncated at midnight instead of extending past it.
<img width="789" alt="Capture d’écran 2024-09-26 à 19 45 11" src="https://github.com/user-attachments/assets/579f1d28-2184-4ecf-8fab-da0d3618727a">

You can view a live demonstration of the issue here:  https://codepen.io/volpeo/pen/MWNYxrj

Any assistance or guidance to resolve this would be greatly appreciated!

**Comment by vkurko** [comment]
Thank you for reporting the issue. The case of `slotMaxTime` expanding to the next day is quite rare, I will look for a solution as soon as possible.

**Comment by vkurko** [comment]
@volpeo please check v3.6.2. I hope the problem is solved.

**Comment by volpeo** [comment]
Works as intended, thank you very much for this release!
