### ISSUE TITLE
Events on local dev are not loaded

### ISSUE THREAD

**Issue by juhas96** [vkurko/calendar#335]
Hello, I tried local development based on this discussion https://github.com/vkurko/calendar/discussions/59#discussioncomment-3623690

Calendar is up and running fine, but events are not loaded, also in console I have error which you can see on image below
<img width="720" alt="Screenshot 2024-09-29 at 23 03 55" src="https://github.com/user-attachments/assets/26e8fdbd-9808-4aec-b422-da3d2d47fc6d">

I checked min.js file from build and it contains that function 'teardown' but I cannot find it at https://cdn.jsdelivr.net/npm/@event-calendar/build@3.5.0/event-calendar.min.js

With https://cdn.jsdelivr.net/npm/@event-calendar/build@3.5.0/event-calendar.min.js everything works fine.

Any suggestions for this? 

I tried to replace teardown with onDestroy, error from console dissapear but events were still not loaded.

Also I found out that this error from build appears only when it is builded from local env, when I unlink node_modules with local packages everything works fine

**Comment by vkurko** [comment]
Please use the commit tagged as `v3.5.0`. The most recent commit was from a recent pull request and has not yet been tested by me.

**Comment by juhas96** [comment]
@vkurko works like a charm, thank you very much, should I close now this issue or left it open as current master branch seems to be broken?

**Comment by vkurko** [comment]
I'm going to close it and will fix the master branch asap.
