### ISSUE TITLE
where can I see ready-made examples?

### ISSUE THREAD

**Issue by f1nderas** [vkurko/calendar#339]
Help please, I want to integrate the calendar into my vue project, but I can't find ready-made examples for quick integration. Where can they be?

**Comment by vkurko** [comment]
Please don't open issues for such kind of questions. The link to [demo](https://vkurko.github.io/calendar/) is available on the project's main page. Its source code is [here](https://github.com/vkurko/calendar/blob/master/docs/index.html).
