### ISSUE TITLE
filterResourcesWithEvents false set problem.

### ISSUE THREAD

**Issue by noneym** [vkurko/calendar#34]
Hello

When I send the following command, the events are filtered, but when I send false, the events do not come back.
ec.setOption('filterResourcesWithEvents', 'true');
ec.setOption('filterResourcesWithEvents', 'false'); --- not working

**Comment by vkurko** [comment]
@noneym You should pass booleans, not strings as the second parameter in `setOption`:

```js
ec.setOption('filterResourcesWithEvents', true);
ec.setOption('filterResourcesWithEvents', false);
```

**Comment by noneym** [comment]
:) its my bad sorry vkurko
Thank you
