### ISSUE TITLE
when i use refetchEvents method can i set set extra param

### ISSUE THREAD

**Issue by noneym** [vkurko/calendar#36]
when i use refetchEvents method, can i set set extra param

for ex;
ec.refetchEvents(hideCancelledEvent);

also 
I tried to write a function in the extraParams part of the eventSources method, it didn't work.

**Comment by vkurko** [comment]
1. No, the `refetchEvents` method does not take any parameters.
2. Can you provide a code example where the `extraParams` does not work?

**Comment by noneym** [comment]
```
 eventSources: [
        {
          url: base_url + "api/appointment_source",
          method: "GET",
          extraParams: {
            cancelled: function () {
              return document.getElementById("switch-1").checked;
            }
          },
   
        },
      ],

```

GET Payload ;
![image](https://user-images.githubusercontent.com/190996/160715119-d00b45f6-3a45-4487-b2d4-5e8fdef7640a.png)

**Comment by vkurko** [comment]
The correct usage of the function would be like this:
```js
eventSources: [
    {
        url: base_url + "api/appointment_source",
        method: "GET",
        extraParams: function () {
            return {
                cancelled: document.getElementById("switch-1").checked ? 1 : 0
            };
        },
    },
],
```

**Comment by noneym** [comment]
thank you vkurko its worked :)
