### ISSUE TITLE
Feature Request - Add possibility to highlight hours in certains day

### ISSUE THREAD

**Issue by Retrovers** [vkurko/calendar#361]
Hi, 

Would it be possible to add a feature to add information between times. This would be useful for example to define a start/end time of the day or a time for lunch?

Here is an example screenshot : 
<img width="1044" alt="Capture d’écran 2024-10-23 à 12 09 30" src="https://github.com/user-attachments/assets/4440d2d4-3db4-40b0-85f2-3b50a9dd4d13">

Have a good day

**Comment by Retrovers** [comment]
It would be nice to be able to configure this per day and per resource.

**Comment by vkurko** [comment]
You can use `background` events for this. To render an event in the background, pass the value `"background"` in the `display` field (see [docs](https://github.com/vkurko/calendar?tab=readme-ov-file#event-object)).

**Comment by vkurko** [comment]
I hope I can close this issue.
