### ISSUE TITLE
Question for background events.

### ISSUE THREAD

**Issue by Bro3x** [vkurko/calendar#362]
Hi there!

I would like to have the opening hours displayed as background events. These background events should not be clickable in any way. Ideally, they shouldn't even show a mouse pointer when hovered over. However, all background events are later overwritten by a pointer. I have tried several combinations of eventContent() and dateClick() without success.

First Object
```
{
    allDay: false,
    backgroundColor: undefined,
    classNames: ['closed'],
    display: "background",
    durationEditable: false,
    editable: false,
    end: Fri Oct 25 2024 14:00:00 GMT+0200 {},
    extendedProps: {},
    id: "o5",
    resourceIds: (7) ['9', '10', '11', '12', '13', '14', '15'],
    start: Fri Oct 25 2024 13:00:00 GMT+0200 {},
    startEditable: false,
    styles: [],
    textColor: undefined,
    title: "closed"
}
```

Overwritten by
```
{
    backgroundColor: "transparent",
    classNames: [],
    display: "pointer",
    end: Mon Oct 21 2024 14:00:00 GMT+0200 {},
    extendedProps: {},
    id: "{pointer}",
    resourceIds: ['12'],
    start: Mon Oct 21 2024 13:30:00 GMT+0200 {},
    styles: [],
    title: ""
}
```

Any hints?

ty

**Comment by vkurko** [comment]
> all background events are later overwritten by a pointer

Can you explain in more detail what you meant here? Better yet, provide an online demo so I can see it live.

**Comment by Bro3x** [comment]
Hier is an example.
https://jsbin.com/kokoziroja/edit?html,js,output
If I click on that background event, the alert should not been fired.

**Comment by vkurko** [comment]
You need to check inside `dateClick` yourself whether `info.date` falls within some background event. Or you can try checking `info.jsEvent.target` for the presence of the `ec-bg-event` class.

```js
dateClick: function (info) {
    if (!info.jsEvent.target.classList.contains('ec-bg-event')) {
      console.log('slot clicked');
    }
}
```

**Comment by Bro3x** [comment]
This is working great, ty.

I have a quick follow-up question:
Is it possible to hide or exclude past days or specific marked days (e.g., bank holidays) in a resourceTimelineWeek view?
In the example above, with today being October 25, 2024, is there a way to hide October 21–24 or Christmas days?

**Comment by vkurko** [comment]
> Is it possible to hide or exclude past days

Unfortunately this is not yet implemented. See #141 

> is there a way to hide October 21–24 or Christmas days?

There is [hiddenDays](https://github.com/vkurko/calendar?tab=readme-ov-file#hiddendays) option but it works for weekdays only.
