### ISSUE TITLE
ScrollTime option doesn't work

### ISSUE THREAD

**Issue by kawasaki656** [vkurko/calendar#363]
I need to scroll to the current time but this option doesn't work at all. Is it functional ?

**Comment by vkurko** [comment]
[Here](https://vkurko.github.io/calendar/) `scrollTime` is `"09:00", doesn't it work for you? Please provide a demo so I can reproduce the issue.

**Comment by kawasaki656** [comment]
@vkurko was able to adjust it. I didn't define height for .ec class, it's important for this feature. Sorry for disturbing

**Comment by vkurko** [comment]
Ok
