### ISSUE TITLE
Summary of events

### ISSUE THREAD

**Issue by coirpower** [vkurko/calendar#365]
Is it possible to display summary of events? I use the calendar for displaying the attendance hours of our staff and it would be great if there is a way to display the weekly summary of hours (events) per resource.

**Comment by vkurko** [comment]
There is no such option. I don't think it will be available out of the box. But it would be nice to have a place where such information could be displayed, for example, [footerToolbar](https://github.com/vkurko/calendar/issues/320). I'll close this issue in favor of #320.
