### ISSUE TITLE
event object background color does not change

### ISSUE THREAD

**Issue by VitorS0uza** [vkurko/calendar#369]
my eventSources is receiving the following json event objects:

`{
                    "id": 12,
                    "backgroundColor": null,
                    "color": null,
                    "resourceIds": 7,
                    "start": "2024-11-01 08:15:00",
                    "end": "2024-11-01 09:05:00",
                    "title": "Corte de Cabelo - Jos\u00e9 Roberto Taguilla",
                    "display": "auto"
                },
                {
                    "id": 13,
                    "backgroundColor": "red",
                    "color": "red",
                    "resourceIds": 7,
                    "start": "2024-11-01 08:15:00",
                    "end": "2024-11-01 09:09:00",
                    "title": "Corte de Cabelo - Jos\u00e9 Roberto Taguilla",
                    "display": "auto"
                }`

![image](https://github.com/user-attachments/assets/789179e6-ba95-42c6-88a3-19afbe6ab49c)

I set both the backgroundColor and color options to test

and, in the calendar, the event appears with the default color.

![image](https://github.com/user-attachments/assets/f0bf7b53-aafe-4f69-8296-1a1e4678087e)

If I change the eventBackgroundColor option, all events change color correctly, however, if I pass "color" in the object event, the event in question does not assume the color.

**Comment by vkurko** [comment]
I prepared a [demo](https://jsbin.com/tivicoguqe/edit?html,output) with your data and I don't see the problem. Can you check?

![image](https://github.com/user-attachments/assets/e572a251-fe72-4a55-9d31-f210a3ac8d36)

**Comment by VitorS0uza** [comment]
I was getting the eventSources through an external function like this:

```
eventSources: [{
                events: function (fetchInfo, successCallback, failureCallback) {
                    loadEvents(fetchInfo, successCallback, failureCallback);
                }
}]
```

And in the loadEvents function I initialized the events of the object I received, but I was not linking the "color" parameter. Banal error.

It is documented here for anyone who ever has a similar problem.

Thank you for your library. It's very good!
