### ISSUE TITLE
eventsources method get event list

### ISSUE THREAD

**Issue by noneym** [vkurko/calendar#37]
Hello,

i am using eventsources  method,
i cant get loaded event list

ec.getOption('events');

this function not wotking when i use eventsources  method also there is no alternative

**Comment by vkurko** [comment]
Hi @noneym 

I'm going to implement a `getEvents()` method :smile:

**Comment by noneym** [comment]
vkurko you are really great, the script is working very well, let me send you a screenshot, there are more than 250 appointments a day and your script is flawless.

![image](https://user-images.githubusercontent.com/190996/161687172-272bc510-b4c3-4f97-8b6f-7c934e34ba51.png)
