### ISSUE TITLE
Dragging an event when 'eventContent' is set, in 'resourceTimelineMonth' view

### ISSUE THREAD

**Issue by Sandbird** [vkurko/calendar#371]
I am having some problems using the 'eventContent' option in order to use the popover in 'resourceTimelineMonth' view.
When I drag the event, the whole event almost disappears as if the height is wrong. I tried fixing it by adding
```
.ec-preview, .ec-ghost {
  height: 24px;
}
```
I've created a demo with the bug described here: https://jsbin.com/tademam/edit?js,output. I've commented out the height, to see it in action.

Furthermore, is there a way i can do something like eventDragging, in order to update the text while dragging to show something like +1 day, +2 days etc untill the user stops dragging?

![image](https://github.com/user-attachments/assets/11eef157-d31c-466f-9073-5d9f1be9bf78)

**Comment by vkurko** [comment]
Just change

```js
eventContent: function(info) {
  return info.event.display === 'auto'
    ? {html: '...'}
    : '';
}
```
to

```js
eventContent: function(info) {
  return info.event.display === 'auto'
    ? {html: '...'}
    : undefined;
}
```

[eventContent](https://github.com/vkurko/calendar#eventcontent) is triggered for absolutely all events, including _helper_ ones, which include the preview when dragging. By returning `undefined` instead of an empty string, you tell the calendar to use the default rendering.


> in order to update the text while dragging to show something like +1 day, +2 days etc untill the user stops dragging

```js
eventContent: function(info) {
  switch (info.event.display) {
    case 'auto':
      return {html: '...'};

    case 'preview':
      return {html: '...'};  // Here you can customize the preview event

    default:
      return undefined;
  }
}
```

**Comment by Sandbird** [comment]
Awesome, thank you for the detailed answer. Makes sense about the 'preview' option, should have thought about it..
