### ISSUE TITLE
What about resource width if I have greater than 15 resources

### ISSUE THREAD

**Issue by NasserHobani** [vkurko/calendar#375]
Hello dear 

if I use the "resourceTimeGridDay" widget and I have more than 15 resources how will I make the minimum width and make the horizontal scroll?

**Comment by NasserHobani** [comment]
this problem
![Screenshot 2024-11-07 112852](https://github.com/user-attachments/assets/a98d0bed-10ca-44e6-b8cb-048a004d1739)

**Comment by vkurko** [comment]
Unfortunately currently this is not possible. A workaround is to use `resourceTimelineXXX` views.

Closing this is favor of #224.
