### ISSUE TITLE
slot height in ressource views not adapting to resource title

### ISSUE THREAD

**Issue by inu-web** [vkurko/calendar#378]
In my implementation the resourcetitle is a html from a template, prefilled with some values e.g.:
```

<div class="ec-resource" role="rowheader" style="flex-basis: 97px;">
	<span>
		<div class="inu-resourcetitle">
			<div class="row g-0">
				<div class="col">
					<div class="pb-1 text-xxsmall">
						<i class="fal fa-home fa-fw fa-lg"></i> <span class'fw-bold'="">Room A1</span>
					</div>
					<div class="pb-1 text-xxsmall">
						<i class="fal fa-user fa-fw fa-lg"></i> Minnie Mouse
						<hr class="m-0">
					</div>
					<div class="pb-1 text-xxsmall">
						<i class="fal fa-clock fa-fw fa-lg"></i> 07:30-18:30
						<hr class="m-0">
					</div>
					<div class="pb-1 text-xxsmall">
						<i class="fal fa-calendar fa-fw fa-lg"></i> 
						<span class="d-inline-block p-1 text-xxsmall border border-1 m-1 moveable" data-id="165" draggable="true" ondragstart="resourcedrag(event)" data-calendar="{&quot;id&quot;:&quot;&quot;,&quot;resourceIds&quot;:[148], &quot;title&quot;:&quot;Drag Donald Duck to the calendar to add a schedule&quot;, &quot;classNames&quot;:&quot;DRAFT&quot;, &quot;extendedProps&quot;:{}}">Donald Duck</span>	 
					</div>
				</div>
			</div>
		</div>
	</span> 
</div>

```
As long as there are no events shown in the calendar, the reource-titles do not expand to show the full content
Only the last resource at the bottom expands to the contents height
![SlotHeight1](https://github.com/user-attachments/assets/a7a54c0e-d9d2-4bf5-b965-45a37bce9bea)

When i add events to the calendar, the slot height expands to the events height
(see screenshots)
![SlotHeight2](https://github.com/user-attachments/assets/40cc03c3-e5d5-46be-a4ce-8efffda68298)

Because the resource title is dynamic in my szenario, I can not use slot height property because it would lead to a lot of unnecessary whitespace for resources that have only 1 or two infos and not all 4 lines 

The last line of this views is working as expected - so I call this an issue because the last line is behaving differently than the other ones.

Any idea or hint to solve this would be highly appreciated - thanks in advance 
Gerald

**Comment by vkurko** [comment]
Can you provide a live demo please? CodeSandbox, StackBlitz, etc

**Comment by LMarcinkowski** [comment]
I have similar problem with resouce height.

![Zrzut ekranu 2024-11-20 o 10 26 17](https://github.com/user-attachments/assets/898d6796-fe0f-4670-a93c-acafd248eba1)

**Comment by vkurko** [comment]
Can you provide a live demo please?

**Comment by vkurko** [comment]
Any update?

**Comment by vkurko** [comment]
Please open a new ticket when the demo is ready.
