### ISSUE TITLE
How to create the Button Group as in the demo page?

### ISSUE THREAD

**Issue by fsoft72** [vkurko/calendar#380]
Hello,

I am not able to find documentation about how to create the same button group that is shown in the event calendar demo.
Which options should I use?

Thanks

**Comment by vkurko** [comment]
Please see [headerToolbar](https://github.com/vkurko/calendar?tab=readme-ov-file#headertoolbar) option. The source code of the demo page can be found [here](https://github.com/vkurko/calendar/blob/master/docs/index.html).
