### ISSUE TITLE
Possibility to display cards in the table side by side.

### ISSUE THREAD

**Issue by derandi80** [vkurko/calendar#387]
Hi, is there a possibility to show the cards in the week table view side by side?
If the cards have a lot of text, it is sometimes hard to read because of the overlapping.

If not, this could be an idea for a future release.

Thanks.

Andreas

**Comment by vkurko** [comment]
Please see [slotEventOverlap](https://github.com/vkurko/calendar?tab=readme-ov-file#sloteventoverlap).

**Comment by derandi80** [comment]
Thx, for the answer @vkurko.
Two additional question, do this option also has an effect on the slots in the all day section?
Can the Drag & Drop function be deactivated? So it is not possible to drag calendar slots into other days?

Thanks

Andreas

**Comment by vkurko** [comment]
> do this option also has an effect on the slots in the all day section?

No.

> Can the Drag & Drop function be deactivated? So it is not possible to drag calendar slots into other days?

Yes. See [eventStartEditable](https://github.com/vkurko/calendar?tab=readme-ov-file#eventstarteditable) option.
