### ISSUE TITLE
Events doesn't hide in responsive

### ISSUE THREAD

**Issue by NuminaAgustin** [vkurko/calendar#390]
Hello, I'm missing a file that controls this type of behavior? I incuded event-calendar.min.css and  event-calendar.min.js in the head section.
I'm working on the "pre-built browser ready bundle" because i inject the whole script, calendar and events on a single line.
I also don't get the "+2 more" message when the events are soposed to be hidden.
I see that in the demo the events get a "visibility: hidden;" property, that in my project isn't included.
Demo:
![image](https://github.com/user-attachments/assets/0150cbdf-d541-46a5-9bba-217dec698232)

My project:
![image](https://github.com/user-attachments/assets/431b46cb-1d4b-4619-93f5-5ada5a0bfcf2)

**Comment by vkurko** [comment]
Did you set [dayMaxEvents](https://github.com/vkurko/calendar?tab=readme-ov-file#daymaxevents) to `true`?

**Comment by NuminaAgustin** [comment]
No I didn't. I tryed and no events are displayed in resposive or desktop.
Here is my func:

`let ec = new EventCalendar(document.getElementById('ec'), {
        view: 'dayGridMonth',
        firstDay: 1,
        eventStartEditable: false,
        eventDurationEditable: false,
		dayMaxEvents: true,
        events: [{
                start: '2024-12-25',
                end: '2024-12-25',
                allDay: true,
                title: 'Feliz Navidad!',
                backgroundColor: 'red'
            }, {
                start: '2024-12-31',
                end: '2024-12-31',
                allDay: true,
                title: 'Feliz 123!',
                backgroundColor: 'blue'
            }, ]
    });`

**Comment by vkurko** [comment]
I prepared a [demo](https://jsbin.com/cedodetuso/edit?html,output) using your code. I can see the events:

![image](https://github.com/user-attachments/assets/eb4fe7fd-2843-48dd-b8e0-1dc24a2d6dd5)

**Comment by NuminaAgustin** [comment]
Thanks! I didn't have the https://vkurko.github.io/calendar/global.css file referenced in my page.
