### ISSUE TITLE
noEventsClick callback doesn't work

### ISSUE THREAD

**Issue by SidunOleh** [vkurko/calendar#391]
Hi, i want to handle event when user clicks on no event area but noEventsClick doesn't work, any idea?

**Comment by gojkogalonjashortcut** [comment]
I also experienced the same issue, and adding noEventsContent does not seem to work.

**Comment by GojkoGalonja** [comment]
I also experienced the same issue, and adding noEventsContent does not seem to work.

**Comment by vkurko** [comment]
I prepared a [demo](https://jsbin.com/dugoxamamo/edit?html,output) with `noEventsClick` and `noEventsContent` and I don't see the problem. Please check.

**Comment by SidunOleh** [comment]
> I prepared a [demo](https://jsbin.com/dugoxamamo/edit?html,output) with `noEventsClick` and `noEventsContent` and I don't see the problem. Please check.

Works only on list view, in other views don't work

**Comment by vkurko** [comment]
Yes, because this is `list` view option only. I think this is mentioned in the docs.

Perhaps you want to handle an event when clicking on a free area inside the calendar. Then look at [dateClick](https://github.com/vkurko/calendar?tab=readme-ov-file#dateclick) option.
