### ISSUE TITLE
Ressources view change after expending nested ressources in timeline

### ISSUE THREAD

**Issue by Toba-bonjour** [vkurko/calendar#393]
Hello,

I'm not sure if this is intended or not but it seems strange to me, 'resources view' changes after expanding nested resources in 'timeline view'.

This should be reproducible with the demo: [https://vkurko.github.io/calendar/](https://vkurko.github.io/calendar/)

I recorded my screen: [https://www.youtube.com/watch?v=PR5RlEFUoMQ](https://www.youtube.com/watch?v=PR5RlEFUoMQ)

**Comment by vkurko** [comment]
Hello. I confirm the issue and will try to fix it asap. Thank you for reporting.

**Comment by vkurko** [comment]
This should be fixed in v3.7.2. Please check.

**Comment by Toba-bonjour** [comment]
Works fine, thanks a lot!
