### ISSUE TITLE
After a resize or any update on previous date tasks it flashes back to current date.

### ISSUE THREAD

**Issue by Betelhemmesele** [vkurko/calendar#399]
when ever i update or delete tasks taht are in the previous dates it flash backs to current date if i want to see the updated task i need to navigate back manually.

**Comment by vkurko** [comment]
Can you provide a live demo please? CodeSandbox, StackBlitz, etc

**Comment by Betelhemmesele** [comment]
It worked by setting the date each time the user navigates between dates.
