### ISSUE TITLE
Cant disable tooltip or popover on drag

### ISSUE THREAD

**Issue by paubikas** [vkurko/calendar#40]
It's not a bug but it will be nice feature that in  eventDragStart that will be "el" selector since popover or tooltip can not be disable while dragging event. So after dropping event in new place tooltip/popover element loses parent element and stays open

**Comment by vkurko** [comment]
I guess you use `eventContent` to initialize the tooltip, right? If yes, did you try to use the `dispay` property of the [Event](https://github.com/vkurko/calendar#event-object) object to catch the `preview` stage of the event while dragging?

**Comment by paubikas** [comment]
Yes I do. I have tried to debug it with console.log and it should work, but it does not.

`eventContent: function (info) {
                return info.event.display === 'auto' ? '<div class="ec-event-time">' + info.timeText + '</div>' + '<div class="ec-event-title">' + info.event.title + '</div>' + '<div hidden class="popover-content">' + info.timeText + '<br>' + info.event.title + '</div>' : '<div class="ec-event-time">' + info.timeText + '</div>' + '<div class="ec-event-title">' + info.event.title + '</div>';
            },
            
            eventDidMount: function (info) {
			
                if (info.event.display === 'auto') {
                    jQuery(info.el).popover({
                        trigger: 'hover',
                        content: function () {
                            return jQuery(this).find('.popover-content').html();
                        },
                        html: true,
                    });
                }

            },`

**Comment by vkurko** [comment]
What about just closing any popover on drag start? See [example](https://jsbin.com/cofezizuzo/edit?js,output).

**Comment by paubikas** [comment]
> What about just closing any popover on drag start? See [example](https://jsbin.com/cofezizuzo/edit?js,output).

Thanks, it is working as it should
