### ISSUE TITLE
Is it possible to implement all day on an event

### ISSUE THREAD

**Issue by conoroshea1996** [vkurko/calendar#41]
Hey thanks for the great library.

Im wondering is there anyway to a full day event.
With the all day bar up the top.
Something like this
![image](https://user-images.githubusercontent.com/47694309/167896710-5001a10b-c36c-4502-b1ab-3b564275cc9d.png)

If it's not possible 
Let me know what it would take to have this feature and I can take a look

Thanks

**Comment by vkurko** [comment]
Unfortunately, this feature has not yet been implemented.

Anyone who needs this feature, please give it :+1:. If the feature is popular, I will implement it.

**Comment by emrahnalci** [comment]
We are see day list on the top right with buttons. Is this button not good for you ?

**Comment by emrahnalci** [comment]
> Unfortunately, this feature has not yet been implemented.
> 
> Anyone who needs this feature, please give it :+1:. If the feature is popular, I will implement it.

Vkurko, how can I click button and add new calendar event i cant do this 
Can you make a demo for me ?

For example I want to click button add 14.00 - 17.00 event than im using now add calendarr event save than page refresh i dont want to this

**Comment by vkurko** [comment]
> For example I want to click button add 14.00 - 17.00 event than im using now add calendarr event save than page refresh i dont want to this

I'm assuming the events are being fetched from the server. In this case, you are doing everything right, but instead of reloading the page, you need to call [refetchEvents()](https://github.com/vkurko/calendar#refetchevents).

**Comment by vkurko** [comment]
> If its possible could you even show how to go about doing something like this where to look in the code ect..
> and I could maybe make a PR.

This should definitely be in the [time-grid](https://github.com/vkurko/calendar/tree/master/packages/time-grid/src) plugin. You may also want to look at the FullCalendar's implementation and its [options](https://fullcalendar.io/docs/allDaySlot) for it.

**Comment by conoroshea1996** [comment]
Hey thanks @vkurko
I've started taking a look at this in more depth.
In terms of adding the all day functionality.

It be great if you could let me know if Im heading in the right direction or if you have different ideas of the implementation of this.

I currently have a setup here locally for just testing a few things.
Some things that seem abit more complex is things like.
 - Dragging from all day back into a time range.
 - Correctly positioning of elements that are multiple days long (grouping them and displaying them across the days)
 - Resizing so that the all day can only be moved across the days when it is an all day event.


I have a very rough draft PR here and Im wondering your thoughts on doing something like this or if you have different ideas.
It be great to have this feature.
- New component for the All Day Body for all the  
- New All Day component which filters on the all day events only


I have a very rough PR here. 
https://github.com/vkurko/calendar/pull/42


https://www.loom.com/share/2c48a9baf8124e47ae3d27aa6f93ffe5

**Comment by vkurko** [comment]
Hi @conoroshea1996 

It's a great start! I think you are moving in the absolutely right direction.

> Dragging from all day back into a time range.

Let's start small and not implement this feature :smile:

Yeah, FullCalendar has a really cool thing about dragging an event from the all-day section to the hourly one. But this will require the implementation of additional options like [allDayMaintainDuration](https://fullcalendar.io/docs/allDayMaintainDuration), [defaultAllDayEventDuration](https://fullcalendar.io/docs/defaultAllDayEventDuration) and so on. In addition, I did not find such a feature in Google Calendar.

So I think it's ok to do just a drag and drop within the all-day section to start with.

> Correctly positioning of elements that are multiple days long (grouping them and displaying them across the days)

It seems that the all-day section should be very similar to the month view. There is an algorithm[[1]](https://github.com/vkurko/calendar/blob/0c42daf7a1414eb4ea3af43946e5079fed834084/packages/day-grid/src/events.js#L4)[[2]](https://github.com/vkurko/calendar/blob/0c42daf7a1414eb4ea3af43946e5079fed834084/packages/day-grid/src/Event.svelte#L86) for arranging intersecting events. Maybe we can somehow share this logic between these two views.

> Resizing so that the all day can only be moved across the days when it is an all day event.

This also looks like a thing that should work the same as in the month view.

---

In addition to the above, I would also change `isAllDay` to `allDay` as it is [called](https://fullcalendar.io/docs/event-parsing) in FullCalendar. And I would also remove the [pointer event](https://github.com/vkurko/calendar/blob/aa8c9b5db3dd46f6b9f13dd160769fb52e117c59/packages/time-grid/src/AllDay.svelte#L143) from the all-day section as it doesn't make much sense there.

---

Other than that, I think it's a great start. Keep it up!

**Comment by conoroshea1996** [comment]
Hey @vkurko 
Great thanks very much for the quick response and feedback.
I'll keep going this way

> Let's start small and not implement this feature 😄

That sounds good I think the dragging from all day to the hourly one isn't worth all the extra effort its not something we need need either at the moment so I'll forget about that  feature😄

> It seems that the all-day section should be very similar to the month view. There is an algorithm[[1]](https://github.com/vkurko/calendar/blob/0c42daf7a1414eb4ea3af43946e5079fed834084/packages/day-grid/src/events.js#L4)[[2]](https://github.com/vkurko/calendar/blob/0c42daf7a1414eb4ea3af43946e5079fed834084/packages/day-grid/src/Event.svelte#L86) for arranging intersecting events. Maybe we can somehow share this logic between these two views.

Great I'll take a look at those some more and see if that works. Thanks for pointing me into the right direction.


> In addition to the above, I would also change `isAllDay` to `allDay` as it is [called](https://fullcalendar.io/docs/event-parsing) in FullCalendar. And I would also remove the [pointer event](https://github.com/vkurko/calendar/blob/aa8c9b5db3dd46f6b9f13dd160769fb52e117c59/packages/time-grid/src/AllDay.svelte#L143) from the all-day section as it doesn't make much sense there.

Noted will updated this also


I'll keep going this way thanks again for the help

**Comment by conoroshea1996** [comment]
Hey @vkurko 
I have made  a few changes to the all day bar.
I've made it similar to how the month view is working now as I think that makes sense?

Would it be possible to have a look at this PR.
Its still abit rough at the moment so I'll do some more cleaning up of it. (There's a few changes I have for running locally)

But Im wondering if you'd be happy to add something like this.

A Demo of it here for you to see 
https://www.loom.com/share/34e3d2dc0f9349628e8c669e06f06254 


Thanks

**Comment by vkurko** [comment]
It looks nice. What about resource view?

Having realized that all-day is essentially a special case of the month view, I think I should refactor the `day-grid` plugin so that it can be used in `time-grid`/`resource-time-grid` without having to duplicate code.

Unfortunately, I don't have enough free time for that right now. But if you can finish your current code, I'll take the PR and do the refactoring myself later.

**Comment by conoroshea1996** [comment]
Hey thanks again for the response.

I've handled the resource view as there now as well.
### Example 
https://www.loom.com/share/f8b8c4c1cc5f49048b4c265123b04165

I agree there's definitely some unnecessary code duplication being done at the moment.
I don't have a deep enough knowledge of the code base to handle cleaning that up and refactoring sorry about that.

That would be great once you have some free time if you could take a look through that PR 
Hopefully it gets some of the extra work done for you.
Its a feature we need for our application currently

I can't spend to much more time on it but hopefully this helps.

Thanks for the replies and for the nice library

**Comment by vkurko** [comment]
> if you could take a look through that PR

I'm going to merge it now, and review and refactor it later. Thanks for yout help!

**Comment by conoroshea1996** [comment]
No worries. Happy to help
Great thanks sounds good.
Yeah it could do with a good once over and review. 
Let me know if I can do anything else to help.

**Comment by conoroshea1996** [comment]
Hey, 
Just wondering would it be possible to release a beta version on to npm of what's currently on master branch.
So we could test out the new feature a bit in our application.
If not no worries.
Thanks again.
😃

**Comment by vkurko** [comment]
Hi Conor. I hope to be able to make time for the calendar tomorrow.

**Comment by conoroshea1996** [comment]
Hey Vladimir that's great thanks for the update.
Sorry for all the messages as well if Im annoying you.

**Comment by vkurko** [comment]
Hey @conoroshea1996 

Unfortunately, I had very little time today, so the big refactoring did not happen. However, I still released a new version of the calendar (0.11.0). Please take a look at the new options [allDayContent](https://github.com/vkurko/calendar#alldaycontent) and [allDaySlot](https://github.com/vkurko/calendar#alldayslot).

Have a nice weekend :smile:

**Comment by conoroshea1996** [comment]
Hey @vkurko 
That looks great nice aswell too add the option docs look good too.
Thanks for your time for releasing a new version
 it's very much appreciated.
Thats brilliant to have that added now

Have a great weekend  😃🥳

**Comment by vkurko** [comment]
I hope I can close this issue.

**Comment by conoroshea1996** [comment]
Ahh yes this issue is solved and thanks again for your hard work
