### ISSUE TITLE
eventDrop broken in v0.11.0

### ISSUE THREAD

**Issue by NoelOConnell** [vkurko/calendar#43]
The `eventDrop` callback has an issue in the latest version.

![image](https://user-images.githubusercontent.com/966495/171619999-cc27c6e7-e5a9-4c9c-aa35-c6d040a8a7ce.png)

`$_viewResources[resourceCol]` throws an error because `$_viewResources` is undefined

Here is a stackblitz example and changing the package version shows it working in v0.10.2
https://stackblitz.com/edit/web-platform-td4v8t?file=index.html

**Comment by vkurko** [comment]
Hi @NoelOConnell 

Thanks for reporting the issue. I've fixed it in v0.11.1.

**Comment by NoelOConnell** [comment]
Thanks @vkurko, v0.11.1 has fixed the issue.
