### ISSUE TITLE
Minimum width and scrollable view for resources in the daily view

### ISSUE THREAD

**Issue by MirwaisAkrami** [vkurko/calendar#47]
Hi @vkurko 

First of all, thank you for the nice work you have done.

I want to have a minimum width for each resource and make them scrollable in the daily resource view.
In my project, I have more than 10 resources in the daily view and they may increase than that as well

![image](https://user-images.githubusercontent.com/34417742/176147034-d5bb388b-ff89-4c4a-a92a-a38e96756120.png)

Is there any way to achieve this in the current configuration set or do I need to do that via custom CSS?

Thank you,

**Comment by vkurko** [comment]
Hi @MirwaisAkrami 

Unfortunately, this feature is currently not available in the calendar. And I doubt that it can be implemented only in CSS.

If you have examples of how such scrolling is implemented in other calendars, I would look at it.

From what is available, I would advise making it possible for the user to hide certain resources in order not to display all of them when there are a lot of them.

**Comment by Sheaffy** [comment]
The above CSS no longer works, however this feature would be super useful, especially in my case where lots of resources are needed to show at the same time.

**Comment by vkurko** [comment]
CSS classes have been improved in the new versions of the calendar. There are now two classes for each view that define the view itself and its variation. For example, for `timeGridWeek` the classes would be `ec-time-grid ec-week-view` and for `timeGridDay` would be `ec-time-grid ec-day-view`. Accordingly, the old `ec-week` class is no longer used. Check out the new classes and update your additional styles accordingly.

**Comment by Sheaffy** [comment]
Well, you saved me multiple hours with that insight, don't know how I missed it.. You got a donation link?

**Comment by vkurko** [comment]
Yes, the [link](https://paypal.me/vkurko) used to be on the main page, but for about a year the amount of donations was $0 :smile: so I removed it. Thank you in advance for your financial support.
