### ISSUE TITLE
How to use it inside angular project

### ISSUE THREAD

**Issue by MirwaisAkrami** [vkurko/calendar#49]
Hi @vkurko, I would like to use the calendar library inside Angular but I couldn't figure it out from the documentation, would you please assist me in this regard.

Thanks

**Comment by vkurko** [comment]
Hi @MirwaisAkrami 

Unfortunately, my experience with Angular was many years ago, and now I can hardly help. If you are well versed in Angular, you may find it useful to look at a similar implementation from [FullCalendar](https://github.com/fullcalendar/fullcalendar-angular/blob/master/projects/fullcalendar/src/lib/fullcalendar.component.ts).

**Comment by MirwaisAkrami** [comment]
Hi @vkurko 
I was able to use it in the angular app with [Pre-built browser ready bundle](https://github.com/vkurko/calendar#pre-built-browser-ready-bundle).
Here are some snippets, in case someone would need them.

1. Add the pre-build browser-ready bundle `js` and `css` files to `index.html`

2. In the component where you want to show the event calendar add
    `declare const EventCalendar: any` at the top of your component **outside the component class, just below the imports.**

3. Add a `<div id="ec"></div` in the component html file

4. Uses the `EventCalendar` variable to initialize the event calendar, preferrably in the `ngAfterViewInit` method like
    `let this.ec = new EventCalendar(document.getElementById('ec'), {
//options
})`

**Comment by vkurko** [comment]
@MirwaisAkrami Thanks for sharing your solution :smile:

**Comment by poke-fcr** [comment]
Thanks for the instant reply @vkurko 

 @MirwaisAkrami If possible can you share the sample code/repo?
Also if you are adding pre-build bundles, do we need to install npm install --save-dev @event-calendar/core ??

I have just started development in angular, pls guide me if i am going in wrong direction..

**Comment by MirwaisAkrami** [comment]
@poke-fcr hi,

No, You don't need to run npm install for that. 

I am sorry, our repo is private to share, but if you follow the steps in my previous comment then you will be good to go. 

Angular is a great framework, I will be glad to help you along the way.

**Comment by joshuaGnol** [comment]
Addon some update on how I get it to works on Angular 19.

- Do the npm install and add the script to index.html.
- in template 
```<div id="ec"></div>```
- in your component, can place under ngAfterViewInit

import EventCalendar from '@event-calendar/core'
import TimeGrid from '@event-calendar/time-grid'

```
const element = this.elementRef.nativeElement.querySelector('#ec')
new EventCalendar({
      target: element,
      props: {
        plugins: [TimeGrid],
        options: {
          view: 'timeGridWeek',
          events: [
            {
              id: '2',
              allDay: true,
              title: 'Long Event'
            }
          ]
        }
      }
    })
```

Hope it helps 🚀
