### ISSUE TITLE
Sunday events are not rendering

### ISSUE THREAD

**Issue by eliluong** [vkurko/calendar#50]
Hello, on my calendar, Sunday events are not rendering and I am not sure why or if there is an option that I missed. I know the events exist inside the `events` property when printing to the console. There are about 2000 events to display in a month, but I reduced the number but it still does not show anything on Sunday. My events are all day events so I set the start/end to be the same date.

Inspecting the source code on a Sunday, there is nothing rendered to events. The other days all have content rendered. Below are my code to render the calendar, and code snippet to generate the array for `events` data. Thank you.

EDIT: I discovered if I do not put a time for `start`/`end` on an event that falls on Sunday, it does not show. But the other days, it does show. (https://jsfiddle.net/b2mj3kxg/2/)

![image](https://user-images.githubusercontent.com/15806938/179828194-addd5a63-7eeb-448b-8a57-6255ec01eaa0.png)

```
async function renderCalendar() {
	let ec = new EventCalendar(document.getElementById('ec'), {
		view: 'dayGridMonth',
		// allDaySlot: true,
		eventStartEditable: false, // disables dragging
		eventContent: eventInfo => {
			// console.log(eventInfo)
			return `<span style='color: ${eventInfo.event.extendedProps.dataColor}'>${eventInfo.event.extendedProps.dataTask} | ${eventInfo.event.extendedProps.dataName}</span>`
		},
		events: renderEvents()
	})
}
```

```
function renderEvents() {
	let events = []
	for (const property in db_main) {
		let d = db_main[property]['date']
		let assignments = db_main[property]['data']
		assignments.forEach(item => {
			events.push({
				start: db_main[property]['date'],
				end: db_main[property]['date'],
				title: 'test',
				allDay: true,
				backgroundColor: item['color'],
				editable: false,
				extendedProps: {
					"dataTask": item['name'],
					"dataName": db_people[item['person']],
					"dataTextColor": item['textColor']
				}
			})
		})
	}
	console.log(events)
	return events
}
```

**Comment by vkurko** [comment]
Hi @eliluong

Thanks for starring the repo and thank you for the jsfiddle example.

The problem is that it was not originally intended that the calendar should display events with zero duration. And in your case, when the start date is equal to the end date, the duration just turns out to be zero.

Yes, it happened by chance that such events were still displayed in the month view, but not on the first day of the week. Therefore, I decided to leave this behavior and fix the display on the first day of the week :smile:

Please check v0.11.2.

Thanks

**Comment by eliluong** [comment]
Thank you, @vkurko I will give it a try.

What was the proper way to create an all-day event? I could not find clear documentation on this. I tried to just use a start date, but it ended up spanning over several days.

**Comment by vkurko** [comment]
> What was the proper way to create an all-day event?

You should set the end date to the beginning of the next day. This should work in your jsfiddle example:
```js
{
    start: "2022-07-03",
    end: "2022-07-04",
    title: "test"
}
```

**Comment by eliluong** [comment]
Thank you for your help!
