### ISSUE TITLE
neither eventClick or  dateClick callback triggered ？

### ISSUE THREAD

**Issue by mutongwu** [vkurko/calendar#52]
It's weired that neither eventClick or  dateClick callback triggered. 

anything wrong?
browser : Chrome 
resources: 
```

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@event-calendar/build/event-calendar-modern.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/@event-calendar/build/event-calendar-modern.min.js"></script>
```

```
      new window.EventCalendar(this.$refs.calendar, {
        view: 'timeGridWeek',
        events: this.createEvents(),
        allDayContent: 'all day.',
        pointer: true,

        dayMaxEvents: true,
        eventClick: function(e) {
          console.log('eventClick', e)
        },
        dateClick(e) {
          console.log('dateClick', e)
        }
      });
```

**Comment by vkurko** [comment]
Everything seems to work fine https://jsbin.com/hoqotalubu/edit?js,output

**Comment by mutongwu** [comment]
> Everything seems to work fine https://jsbin.com/hoqotalubu/edit?js,output

Thanks you for you reply. It's my mistake. I haven't noticed console messages were filtered . 😅

By the way, it's a nice project.  And it will be much better to have more demo for it has so many options . Group the options into a few ones might be more clear.

**Comment by vkurko** [comment]
@mutongwu Thanks for the tips, I'll definitely take them into account in the future.

**Comment by noneym** [comment]
I have the same problem. When you click on dateclick, event click is also activated. The noeventclick function does not work in this case.
