### ISSUE TITLE
GetEvents changes start and end values

### ISSUE THREAD

**Issue by AdrianGzzEsc** [vkurko/calendar#55]
Every time I call the getEvents function it changes the start and end hours. Also is it possible to save dates as strings since it always converts it into a date value. Right now to solve this problem I have to run a function after calling the getEvents so I can reformat the dates into "aaaa/mm/ddT17:30" saving it like this works and displays everything correctly.

A solution I can give is that the addEvent, editEvent also adds/updates the ec.event array and that the getEvents function just looks for ec.event array

**Comment by vkurko** [comment]
Hi @AdrianGzzEsc 

Could you prepare a [JS Bin](https://jsbin.com/) (or [JSFiddle](https://jsfiddle.net/), etc) example please, so that I can reproduce the issue?

Thanks

**Comment by vkurko** [comment]
I hope I can close this issue.
