### ISSUE TITLE
Resource Time Grid for multiple days

### ISSUE THREAD

**Issue by autech-greg** [vkurko/calendar#60]
Is it possible to have a resourceView that works like resourceTimeGridDay, but has the timeslots as days instead of hours?

I have a use-case where I have multiple resources that can be booked out over days (not hours). I am trying to get the event-calendar to display this.

So far by using the following code below, I get close to what I want, but dragging seems broken and I can't figure out how to change the time text to show dates instead

`window.ec = new EventCalendar(document.getElementById('cal-view'), {
        view: 'resourceTimeGridDay',
        //slotDuration:'12:00:00',
        //duration:(1000),
        height: '1000px',
        slotMinTime:{day:-2},
        slotHeight: 48,
        slotMaxTime:{month:1},
        slotDuration:{day:1},
        datesAboveResources:true,
        resources: [
            {id:1, title:'Object 1'},
            {id:2, title:'Object 2'},
            {id:3, title:'Object 3'},
            {id:4, title:'Object 4'},
        ],
        events: createEvents()
    });`

![Screen Shot 2022-10-11 at 12 32 26 pm](https://user-images.githubusercontent.com/90439896/194977455-5a48ee26-2228-42d8-9524-84a926ba0f6e.png)

Update: Discovered 'slotLabelFormat', however the dates seem to be going from the 1st of Jan 2020, in addition, I've noticed that events that span multiple days are not rendering as such.

**Comment by vkurko** [comment]
@autech-greg Yes, it was not intended that periods expressed in days would be used in `timeGrid` views. That is why the time scale on the left is really not tied to the current date, but an arbitrary date 2020-01-01 is used. Maybe I should change this logic.

For other issues, try setting the `slotDuration` as `{hours: 24}`, because the value of seconds is used in this view, and the number of days is not taken into account..

**Comment by autech-greg** [comment]
@vkurko Thanks for your reply.
Yes setting the slotDuration to hours:24 resolved the additional issues. I shall do some experiments to see if I can use slotLabelFormat to use current dates instead.

Cheers

**Comment by vkurko** [comment]
`slotLabelFormat` supports using a function as a value. I think that in this function you can use the current date plus an offset in days to display the correct label.

**Comment by vkurko** [comment]
I hope I can close this ticket.
