### ISSUE TITLE
When Its the first of the month the map view is wrong

### ISSUE THREAD

**Issue by AdrianGzzEsc** [vkurko/calendar#63]
![evidenceCalendar](https://user-images.githubusercontent.com/32023754/199538718-5720e71d-d596-43fc-801c-a13cda646ed7.png)

The image is from your demo, it was happening to me too so I went to the demo to see if it was not something I mess up.  As you can see in the image, Its november 1st and the first days of the months appear all the way at the bottom. This only happens when its the first of the month

**Comment by vkurko** [comment]
Hi @AdrianGzzEsc 

I tried to reproduce the problem, but I didn't succeed. I changed the date on my computer to November 1st, but the calendar still displayed without issues.

Maybe information about your environment will help reproduce the problem. Please tell me the version of your browser and the time zone configured on your computer. Thanks.

**Comment by AdrianGzzEsc** [comment]
Hello, this was happening to every user.
User browsers: Brave, Safari, Chrome, Opera

I think you couldnt replicate it since its the server time and not the
computer? Was Nobember 1st highlated?

**Comment by vkurko** [comment]
@AdrianGzzEsc what is your time zone?

**Comment by AdrianGzzEsc** [comment]
Central Standard Time
Time zone in Ciudad Apodaca, Nuevo Leon (GMT-6)
Wednesday, November 2, 2022, 15:03

**Comment by vkurko** [comment]
> Central Standard Time
> Time zone in Ciudad Apodaca, Nuevo Leon (GMT-6)
> Wednesday, November 2, 2022, 15:03

Thanks, I could reproduce it in your time zone. I will release an update as soon as I fix the bug.

**Comment by vkurko** [comment]
@AdrianGzzEsc the issue should be fixed in v0.13.2. Please check.

**Comment by vkurko** [comment]
I hope I can close this issue.
