### ISSUE TITLE
NowIndicator doesn't update when new day arrives

### ISSUE THREAD

**Issue by timsu** [vkurko/calendar#64]
When the calendar is open for more than a day, the NowIndicator stays on the original day the calendar was initialized to, and does not move to the new day. You can also reproduce this by changing the date on your computer and then causing a re-render - the indicator still shows on the previous day.  If it matters, I'm using the `timeGridDay` view.

I believe this is because of Day.svelte `isToday` not being correct, but I'm not a svelte person so I'm entirely sure how that works.

**Comment by vkurko** [comment]
Hi @timsu 

Thanks for reporting the issue. I was able to reproduce it.

In the new version 0.13.4 the problem should be fixed. Please check.

**Comment by timsu** [comment]
Just tested it, it's fixed! Thanks so much 🙏
