### ISSUE TITLE
Overflow in Calendar

### ISSUE THREAD

**Issue by AdrianGzzEsc** [vkurko/calendar#65]
![image](https://user-images.githubusercontent.com/32023754/201978127-cd3ff5f5-50a6-41c1-9a8e-a8504caa2499.png)

I wanted to know if its possible to add all the events in the map and be able to see them while scrolling instead of having the "6 more" tag. I added overflow but only increasing the height make it display more events.

**Comment by vkurko** [comment]
Hi @AdrianGzzEsc 

If you set [dayMaxEvents](https://github.com/vkurko/calendar#daymaxevents) to `false` (which is the default value) then the `6 more` link should not be displayed.

**Comment by vkurko** [comment]
I hope I can close this issue.
