### ISSUE TITLE
ES6 import styles?

### ISSUE THREAD

**Issue by smallst** [vkurko/calendar#66]
can i import styles in es6 instead of using pre-build jsdelivr url ? if so. which file should i import ? `node_modules/@event-calendar/core/index.css` ?

**Comment by vkurko** [comment]
Yes, the CSS is located at `@event-calendar/core/index.css`. If your build tool supports CSS processing, you can import it like:

```js
import '@event-calendar/core/index.css';
```

**Comment by smallst** [comment]
thanks! i found it. maybe worth adding this info in readme so that everyone could make sure with it 😄

**Comment by vkurko** [comment]
> maybe worth adding this info in readme so that everyone could make sure with it

Done :smile:
