### ISSUE TITLE
"You may need an appropriate loader to handle this file type"

### ISSUE THREAD

**Issue by ShetlandJ** [vkurko/calendar#73]
I am getting this breaking error when trying to use calendar in a Vue 2 / Laravel mix application. I think it's because of the null coalesing operator.

The full error is as follows:

![image](https://user-images.githubusercontent.com/29278616/210082420-5f4af889-5f3f-4e21-b999-a76cd4cb3db1.png)

The code used is:
```
<script>
import Calendar from '@event-calendar/core';
import TimeGrid from '@event-calendar/time-grid';
import Interaction from '@event-calendar/interaction';
import '@event-calendar/core/index.css';

export default {
    mounted() {
        const ec = new Calendar({
            target: document.getElementById('ec'),
            props: {
                plugins: [TimeGrid, Interaction],
                options: {
                    view: 'timeGridWeek',
                    slotMinTime: '07:00:00',
                    slotMaxTime: '20:00:00',
                    events: [
                        {
                            id: 1,
                            title: 'Event Title',
                            start: new Date('2022-12-30T13:00:00'),
                            end: new Date('2022-12-30T15:00:00'),
                            allDay: false,
                        },
                    ],
                },
            },
        });
    },
};
</script>
```

I searched the issues list and couldn't find that anyone else had had this issue. I would appreciate any suggestions!

**Comment by vkurko** [comment]
I hope I can close this issue.

**Comment by vkurko** [comment]
> same issues with node v14.21.2 npm 6.14.17

Can you show the error log please? Nullish coalescing operator (??) is supported in node v14.21.2.

**Comment by ginkosen** [comment]
```
Module parse failed: Unexpected token (1597:59)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 	function setPopupChunks() {
| 		let nextDay = addDay(cloneDate(date));
> 		let chunks = dayChunks.concat(longChunks[date.getTime()]?.chunks || []);
| 		set_store_value(_popupChunks, $_popupChunks = chunks.map(chunk => assign({}, chunk, createEventChunk(chunk.event, date, nextDay), { days: 1, dates: [date] })).sort((a, b) => a.top - b.top), $_popupChunks);
| 	}

```

```
Module parse failed: Unexpected token (351:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 				(selecting()
| 				? $selectLongPressDelay
> 				: $eventLongPressDelay) ?? $longPressDelay
| 			));
| 		}


```

**Comment by vkurko** [comment]
> ```shell
> ~ %node -v                                                                                                                                                                                                               
> v14.21.2
> ~ %npm -v                                                                                                                                                                                                                 
> 6.14.17
> ```

May you have different versions of nodejs installed on your system and webpack is using an older version?

Version 14.21.2 can't have these errors because [Optional chaining (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and [Nullish coalescing (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) both are supported since version 14.0.0.

![image](https://user-images.githubusercontent.com/1073174/223945699-58e7737b-a0b6-44c3-84c8-8e68a246f1de.png)
![image](https://user-images.githubusercontent.com/1073174/223945781-26f72a27-4dd1-472a-aa3d-08aaeb2fa369.png)

**Comment by ginkosen** [comment]
> [Optional chaining (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)


Ohhh,maybe i get it.

In my project the dev dependencies like this.

```
"@babel/core": "^7.17.10",
"@babel/preset-env": "^7.10.4",
"@babel/register": "^7.17.7",
"webpack": "^4.43.0",
"webpack-cli": "^3.3.12"
```

**Comment by vkurko** [comment]
In theory, this is possible. But I'm not sure how this is in line with accepted practices. You would like ES5, but someone else doesn't. Now the package delivers the code as it is, and then everyone, for example, using Babel, can compile the version they need.

**Comment by ginkosen** [comment]
> In theory, this is possible. But I'm not sure how this is in line with accepted practices. You would like ES5, but someone else doesn't. Now the package delivers the code as it is, and then everyone, for example, using Babel, can compile the version they need.

Thanks for replay . I get it.

This issues is cause by babel config is not transform node_modules files.

Thanks again.
