### ISSUE TITLE
Month view stop working

### ISSUE THREAD

**Issue by AdrianGzzEsc** [vkurko/calendar#74]
Im using cdn, not sure if you just drop an update on it but my calendar month view stop working without any changes. I figure out I have to add display: contents to the .ec-body class to get it back working. The week and day view were working okey

https://snipboard.io/kFeWab.jpg

**Comment by vkurko** [comment]
In v0.15.0 I dropped support for IE. Do you have this issue reproduced on [demo](https://vkurko.github.io/calendar/)?

**Comment by AdrianGzzEsc** [comment]
> In v0.15.0 I dropped support for IE. Do you have this issue reproduced on [demo](https://vkurko.github.io/calendar/)?

No, I took a look and demo was working fine. I was making some changes in localhost and after 3pm the calendar stop showing. I removed my changes to see what was going on but still the same. Then I took a look into the main web page and the calendar was gone too, without pushing any changes. Luckily it was just a css fix, thank you for the cdn link, I was going to ask how to stop auto-updates

**Comment by altasB2** [comment]
> In v0.15.0 I dropped support for IE. Do you have this issue reproduced on [demo](https://vkurko.github.io/calendar/)?

To reproduce it, initialize the calendar using example in Pre-built browser ready bundle, and setting the view to "dayGridMonth"

After setting the height, the days will start showing again.

**Comment by vkurko** [comment]
> > In v0.15.0 I dropped support for IE. Do you have this issue reproduced on [demo](https://vkurko.github.io/calendar/)?
> 
> To reproduce it, initialize the calendar using example in Pre-built browser ready bundle, and setting the view to "dayGridMonth"
> 
> After setting the height, the days will start showing again.

Thanks a lot for the tip. I fixed this issue in version 0.15.1. Please check.

I also corrected the README so that the code for cdn specifies the version of the library.

**Comment by vkurko** [comment]
I hope I can close this issue.
