### ISSUE TITLE
Vue, React Support ?

### ISSUE THREAD

**Issue by chirumist** [vkurko/calendar#75]
How to use this package in vue or react.

**Comment by vkurko** [comment]
Currently, the distribution version of the library is pure JavaScript. In fact, even for Svelte, the library does not provide any separate API (for example, slots), although the calendar itself is written in Svelte.

But even though there are no wrappers for other frameworks, you can use the calendar like any other pure JS library. The initialization of the calendar will most likely be in a hook that fires when your component is mounted in the DOM.
