### ISSUE TITLE
How to fetch events from API?

### ISSUE THREAD

**Issue by oendnsk675** [vkurko/calendar#76]
How to fetch events from API?

**Comment by vkurko** [comment]
Please take a look at the [eventSources](https://github.com/vkurko/calendar#eventsources) option.

It allows you to specify a url where the calendar will send requests for new events. You can also set your own function, inside which you can request events from the source you need and return the result to the calendar.

**Comment by oendnsk675** [comment]
`
EventSource: [{
            url: 'http://127.0.0.1:5000/api/schadule',
            method: 'GET',
            events: function(fetchInfo, successCallback, failureCallback) { 
                alert()
            },
        }]
`

i am using that configuration but not getting any response, is there something wrong with my configuration?

**Comment by vkurko** [comment]
The `eventSources` can be either like this:

```js
eventSources: [
    {
        url: 'http://127.0.0.1:5000/api/schadule',
        method: 'GET'
    }
]
```

or like this

```js
eventSources: [
    {
        events: function(fetchInfo, successCallback, failureCallback) {
            // do your own fetch &
            // return array of events
        }
    }
]
```

You must choose one option and do not mix them :smile: I hope this makes sense.

**Comment by oendnsk675** [comment]
Thankyou bro
