### ISSUE TITLE
Selectable Not Working in Svelte

### ISSUE THREAD

**Issue by lrfahmi** [vkurko/calendar#77]
Unable to use in Svelte. Try in svelte repl, error message: Unexpected token (Note that you need plugins to import files that are not JavaScript)

**Comment by vkurko** [comment]
Can you provide a link to the repl?

**Comment by lrfahmi** [comment]
https://svelte.dev/repl/1bea20310a654f48ab9e61f78af4adc2?version=3.55.1

**Comment by vkurko** [comment]
> I'am try install to my svelte project is successfull, but selectable not working.

It is [disabled](https://github.com/vkurko/calendar#selectable) by default. Did you try `selectable: true`? Also you need to use `@event-calendar/interaction` plugin for selection to work.

**Comment by lrfahmi** [comment]
I have activated it in options

```
let options = {
view: 'timeGridWeek',
selectable: true,
events: [
	// your list of events
]
};
```
Any configuration after installing this @event-calendar/interaction package?

**Comment by vkurko** [comment]
You should pass `Interaction` in the list of plugins on initialization.

```svelte
<script>
    import Calendar from '@event-calendar/core';
    import TimeGrid from '@event-calendar/time-grid';
    import Interaction from '@event-calendar/interaction';

    let plugins = [TimeGrid, Interaction];
    let options = {
        view: 'timeGridWeek',
        selectable: true,
        events: [
            // your list of events
        ]
    };
</script>

<Calendar {plugins} {options} />
```

**Comment by vkurko** [comment]
I hope I can close this issue.
