### ISSUE TITLE
hover popover not working

### ISSUE THREAD

**Issue by emrahnalci** [vkurko/calendar#79]
Hi Vladimir,
Calendar build V0.15 version popover not working with bootstrap 5 and jquery 3.6.3....
But working build@0.10.2 with jquery-3.5.1.slim.min and bootstrap@4.6.1

Can you check ? 
I cant do this :(
![Adsız](https://user-images.githubusercontent.com/6512956/215293523-229556b6-58d2-4243-8177-075f0f94b577.jpg)

**Comment by vkurko** [comment]
From your screenshot, it seems to me that your application was affected by changes in version [0.14.0](https://github.com/vkurko/calendar/blob/master/CHANGELOG.md#0140).

Pay attention to these 2 points:

* :warning: The [Event](https://github.com/vkurko/calendar#event-object) object now has a separate `titleHTML` field to render the HTML version of the title, and the original `title` field will now be rendered as text
* :warning: [eventContent](https://github.com/vkurko/calendar#eventcontent) and similar settings now render the string as plain text instead of HTML. To render HTML, you must pass it as `{html: '<p>...</p>'}`

**Comment by emrahnalci** [comment]
Hi Vladimir,
I did as you said before but it doesn't work.
Can you fix this please i dont understan 

[https://codepen.io/emrahnalci/pen/PoBBXym](url)

**Comment by vkurko** [comment]
It seems that you need to refer to the Bootstrap documentation because popovers in version 5.3 are [initialized](https://getbootstrap.com/docs/5.3/components/popovers/#usage) differently.

**Comment by emrahnalci** [comment]
Yesss i solved the problem. @vkurko but i can't make this problem .s

My codes;
`eventContent: function(info) {
            return info.event.display === 'auto'
                ? 
                '<div class="ec-event-time">' + new Date(info.event.start).toLocaleTimeString('en-GB') + '</div>' +
                '<div class="ec-event-title">Başlık</div>' +
                '<div hidden class="popover-contents">popover title</div>' +
                '<div hidden class="popover-content">popover explanation</div>'
                : new Date(info.event.start).toLocaleTimeString('en-GB');
        },
        eventDidMount: function(info) {
            if (info.event.display === 'auto') {
                const bsPopover = new bootstrap.Popover(info.el, {
                    placement: 'left',
                    trigger: 'hover',
                    html: true,
                    title: 'dsa',
                    content: `<h4>Hello World!</h4>`
                });

                info.event.titleHTML = 'dsadsadsa '

                /*
                new bootstrap.Popover(info.el, {
                    trigger: 'hover',
                    html: true,
                    title: function(){
                        return $(this).find('.popover-contents').html();
                    },
                    content: function() {
                        return $(this).find('.popover-content').html();
                    }
                });
                */
            }
        },
        eventDragStart: function (info) {
            $('.ec-event').Popover('hide');
        },`

⚠️ The [Event](https://github.com/vkurko/calendar#event-object) object now has a separate titleHTML field to render the HTML version of the title, and the original title field will now be rendered as text
⚠️ [eventContent](https://github.com/vkurko/calendar#eventcontent) and similar settings now render the string as plain text instead of HTML. To render HTML, you must pass it as {html: '<p>...</p>'}

**Comment by vkurko** [comment]
You should return an object with `html` field. Like this:
```js
eventContent: function(info) {

  return {
    html: info.event.display === 'auto'
      ? '<div class="ec-event-time">' + new Date(info.event.start).toLocaleTimeString('en-GB') + '</div>' +
        '<div class="ec-event-title">Başlık</div>' +
        '<div hidden class="popover-contents">popover title</div>' +
        '<div hidden class="popover-content">popover explanation</div>'
      : new Date(info.event.start).toLocaleTimeString('en-GB') + ' - ' + new Date(info.event.end).toLocaleTimeString('en-GB')
  };

}
```

**Comment by emrahnalci** [comment]
Yess now it's workingg 
Thank youuu 💯 👍🏼
