### ISSUE TITLE
Resource Grid Select Function return wrong value

### ISSUE THREAD

**Issue by weiliang79** [vkurko/calendar#81]
Hi Vladimir,
In the resource day or week grid when select on first resource timeline the function return '0' instead of the resource info.
![Screenshot 2023-01-30 175839](https://user-images.githubusercontent.com/51218866/215446574-28af6898-2f79-45c5-b264-f750c8b4d4aa.png)

The first console log is selecting on the first resource timeline and the resource value becomes '0', and the second console log is selecting the second or other resource timeline and the resource are obtained properly.

**Comment by vkurko** [comment]
Thanks for reporting the bug. It should be fixed in version 0.15.3. Please check.

**Comment by weiliang79** [comment]
You're welcome, and thanks for quick response and bug-fixing.
