### ISSUE TITLE
Unusual Behaviour

### ISSUE THREAD

**Issue by AdrianGzzEsc** [vkurko/calendar#85]
Heres a video: https://clipchamp.com/watch/WLFnXRSIkbj

Could you explain how it performs the moving action to know if I modify something important that could cause this kind of behaviour. This is not happening on the demo so If you have any idea what could cause it I will really appreciate it

**Comment by vkurko** [comment]
I can only help if you provide a demo on jsbin/jsfiddle/codepan or similar service.

**Comment by vkurko** [comment]
Unfortunately, it's hard to say why you have this behavior. I can only help if you provide a demo on jsbin/jsfiddle/codepen or similar service.

**Comment by AdrianGzzEsc** [comment]
There you go: https://codepen.io/AdrianGzzEsc/pen/ExePXxR

You can only move red ones and it will ask you to confirm the change. Thank you very much for all your support so far

**Comment by vkurko** [comment]
I see 2 problems:
1. You are adding extra DOM nodes for `resumen` which breaks the internal structure of the calendar. The drag&drop feature is designed for a specific node structure, so it breaks when the structure is broken.
2. I'm pretty sure that by adding vertical scrolling to the calendar cells, you also broke drag&drop because it wasn't designed for that.

**Comment by AdrianGzzEsc** [comment]
Thank you very much, it was just the added DOM element messing things up. Now I got it working as I wanted!

**Comment by vkurko** [comment]
Thanks for providing codepen demo. On your data, I noticed a problem with the positioning of events in the calendar:

![image](https://user-images.githubusercontent.com/1073174/220320869-95bf758d-6827-4649-a089-4cf2e9ba4f09.png)

I will try to fix this in the next release.

**Comment by AdrianGzzEsc** [comment]
I updated the codepen so you can notice another problem.

`                eventDragStart: function (info){
                    revert = JSON.parse(JSON.stringify(info.event))
                    var day = convert(info.event.start).split('-')
                    if (parseInt(day[2]) > datePicked) 
                        day[1] = parseInt(day[1]) + 1
                        day[2] = datePicked

                    day = day.join('-')
                    info.event.start = day + " 07:30"
                    info.event.end = day + " 17:30"
                    ec.updateEvent(info.event)
                },
                eventDrop: function (info) {
                    if(!confirm('Deseas modificar esta tarea para el ' + convert(info.event.start) + "?")){
                        ec.updateEvent(revert)
                    } else {
                    info.event.start = convert(info.event.start) + " 07:30"
                    info.event.end = convert(info.event.start) + " 17:30"
                    ec.updateEvent(info.event)
                    updatePlanProduccion(info.event)
                    }
                }`

Since Im updating the event on the eventDragStart I cant use info.revert() on eventDrop function. So what I do its to create a copy of the object and store it in "revert" variable so I can use it later on the eventDrop. If I drag the event to different places and revert it, the second time reverting it always adds a day to the event and then the third one moves it one day.

Heres a video: https://clipchamp.com/watch/HXIb1Z9uLMc

**Comment by vkurko** [comment]
> I updated the codepen so you can notice another problem.

Could you create a separate issue for this please?

**Comment by vkurko** [comment]
> Thanks for providing codepen demo. On your data, I noticed a problem with the positioning of events in the calendar:
> 
> ![image](https://user-images.githubusercontent.com/1073174/220320869-95bf758d-6827-4649-a089-4cf2e9ba4f09.png)
> 
> I will try to fix this in the next release.

This should be fixed in v0.16.1.
