### ISSUE TITLE
Event info not getting correctly

### ISSUE THREAD

**Issue by AdrianGzzEsc** [vkurko/calendar#87]
I updated the codepen so you can notice another problem: https://codepen.io/AdrianGzzEsc/pen/ExePXxR

`               eventDragStart: function (info) {
                    revert = JSON.parse(JSON.stringify(info.event))
                    var day = convert(info.event.start).split('-')
                    if (parseInt(day[2]) > datePicked) 
                        day[1] = parseInt(day[1]) + 1

                    day[2] = datePicked
                    day = day.join('-')
                    info.event.start = day + " 07:30"
                    info.event.end = day + " 17:30"
                    ec.updateEvent(info.event)
                },
                eventDrop: function (info) {
                    if(!confirm('Deseas modificar esta tarea para el ' + convert(info.event.start) + "?")){
                        ec.updateEvent(revert)
                    } else {
                    info.event.start = convert(info.event.start) + " 07:30"
                    info.event.end = convert(info.event.start) + " 17:30"
                    ec.updateEvent(info.event)
                    updatePlanProduccion(info.event)
                    }
                }`

Since Im updating the event on the eventDragStart I cant use info.revert() on eventDrop function. So what I do its to create a copy of the object and store it in "revert" variable so I can use it later on the eventDrop. If I drag the event to different places and revert it, the second time reverting it always adds a day to the event and then the third one moves it one day.

Heres a video: https://clipchamp.com/watch/HXIb1Z9uLMc

**Comment by AdrianGzzEsc** [comment]
Any news on this?

**Comment by vkurko** [comment]
The issue here is that Event Calendar does not currently support time zones in date strings.

When you do a `JSON.stringify` on an event object, its start and end dates are converted to a string in the UTC time zone. Such strings are then misinterpreted when you pass them back to the Event Calendar.

Therefore, I advise for now to copy the event as follows:

```js
revert = cloneEvent(info.event);

function cloneEvent(event) {
    event = Object.assign({}, event);
    event.start = cloneDate(event.start);
    event.end = cloneDate(event.end);

    return event;
}

function cloneDate(date) {
    return new Date(date.getTime());
}
```

**Comment by AdrianGzzEsc** [comment]
Thank you very much, it worked perfectly

**Comment by vkurko** [comment]
Great 😄
