### ISSUE TITLE
Cannot initialize code to run locally online

### ISSUE THREAD

**Issue by nperezfernandez** [vkurko/calendar#89]
Hey, 

Thank you so much for creating this, it is a super helpful too!

I followed your instructions to try to make it run locally and unfortunately nothing shows up on http://localhost:5173/. I was wondering if you could provide any other more exhaustive instructions as to how to get the code to run properly and show the calendar in the first place. Thank you so much.

**Comment by vkurko** [comment]
Hi @nperezfernandez  

If you want to run a calendar in your application, then the [documentation](https://github.com/vkurko/calendar#usage) describes the steps for different configurations, such as Svelte, ES6, etc.

If you want to download the calendar source repository and run the calendar from there, here are the steps to take:

After you download the code to your computer, you need to install the dependencies

```bash
npm install
```

then create web root directory and prepare assets

```bash
cp -r docs public
ln -s ../packages/build public/build
```

then edit `public/index.html` and replace the lines

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@event-calendar/build@0.16.1/event-calendar.min.css">
<script src="https://cdn.jsdelivr.net/npm/@event-calendar/build@0.16.1/event-calendar.min.js"></script>
```

with

```html
<link rel="stylesheet" href="build/event-calendar.min.css">
<script src="build/event-calendar.min.js"></script>
```

then start the dev server

```bash
npm run dev
```
and access it at http://localhost:8080/.

**Comment by nperezfernandez** [comment]
Hey,

Thank you so much. I am actually trying to run the calendar in my application as a component. I was wondering if there was any chance you would be free for a consultation as I really love your project. This is my email nicopfcyluna@gmail.com, would love to talk more

**Comment by vkurko** [comment]
> I am actually trying to run the calendar in my application as a component.

I've prepaid a demo with SvelteKit [here](https://stackblitz.com/edit/sveltejs-kit-template-default-mvpsgx?file=src/routes/+page.svelte). Everything seems to work fine. Can you check?

**Comment by vkurko** [comment]
I hope I can close this issue.
