### ISSUE TITLE
Is it possible to do "Resource Timeline" as FullCalendar with your component ?

### ISSUE THREAD

**Issue by frck006** [vkurko/calendar#92]

**Comment by frck006** [comment]
Thank you for your svelte component which is very similar of FullCalendar.
I wonder if it is possible to do the same thing like "Resource Timeline" with your component as is ?
Is it possible to permute day/resource with hour ?
![image](https://user-images.githubusercontent.com/10244725/224511001-84d8b32e-72fe-401c-955b-e4d19dd788e2.png)

**Comment by vkurko** [comment]
Hi @frck006 
Unfortunately, this view is currently unavailable. There is already an open [issue](#30) about this, so I'm closing this one in favor of the previous one. Please vote there for the implementation of this functionality.
