### ISSUE TITLE
using Content-Security-Policy

### ISSUE THREAD

**Issue by chungyentsai** [vkurko/calendar#97]
I'm having issues while using Content-Security-Policy, style-src 'self'; Is there a way to avoid using inline styles without adding 'unsafe-inline'? 

The code I'm using is this, the HTML is almost identical to the demo

[index.html](https://docs.google.com/document/d/1dQ2vbW721XbVioeUvHe3K3lbv_q9hR_gPYmlQ6bzlto/edit)

The JS, CSS, and jQuery are used on local.
calendar.js add document.ready function, then everything is same :

`
$( document ).ready(function() {
        let ec = new EventCalendar(document.getElementById('ec'), {
        .........
        }
});
`

[jquery](https://code.jquery.com/jquery-3.6.4.js)

In browser it throws on console:
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).  event-calendar.min.js:5:16396   and  event-calendar.min.js:5:15863

[stackblitz](https://stackblitz.com/edit/web-platform-hjzevq?file=index.html)
not run in stackblitz, but can set the proyect like this and run on local

**Comment by vkurko** [comment]
Unfortunately, inline styles are used to position events within the calendar. Most likely there is no other solution than to allow inline styles with `unsafe-inline`.

**Comment by chungyentsai** [comment]
What a shame, thank you very much
